-- 001_roles_permissions.sql (Prompt 2.2)
-- GENERATED — do not hand-edit. Regenerate with:
--   node scripts/generate-role-permission-seed.mjs
-- Source: docs/permission-catalog.json v1 (182 permissions, 7 roles).
-- Idempotent: every INSERT is ON CONFLICT DO NOTHING, safe to re-run.

INSERT INTO roles (key, label_en, label_bn, level, is_system) VALUES
  ('super_admin', 'Super Admin', 'সুপার অ্যাডমিন', 100, true),
  ('admin', 'Admin', 'অ্যাডমিন', 80, true),
  ('moderator', 'Moderator', 'মডারেটর', 60, true),
  ('editor', 'Editor', 'এডিটর', 60, true),
  ('supplier', 'Supplier', 'সরবরাহকারী', 20, true),
  ('saler', 'Saler', 'সেলার', 20, true),
  ('customer', 'Customer', 'ক্রেতা', 10, true)
ON CONFLICT (key) DO NOTHING;

INSERT INTO permissions (key, domain, label_en, label_bn, plain_en, plain_bn, risk_tier, delegable, approval_mode) VALUES
  ('users.account.view', 'users', 'View user accounts', 'ইউজার অ্যাকাউন্ট দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('users.account.view_pii', 'users', 'View personal identity data', 'ব্যক্তিগত পরিচয় তথ্য দেখা', 'see NID numbers, bank accounts and KYC documents', 'এনআইডি নম্বর, ব্যাংক অ্যাকাউন্ট ও কেওয়াইসি নথি দেখতে', 'HIGH', true, 'approve_before'),
  ('users.account.edit', 'users', 'Edit user accounts', 'ইউজার অ্যাকাউন্ট সম্পাদনা', 'change another user''s profile details', 'অন্য ইউজারের প্রোফাইল তথ্য পরিবর্তন করতে', 'MEDIUM', true, 'approve_before'),
  ('users.account.penalise', 'users', 'Issue warnings and strikes', 'সতর্কতা ও স্ট্রাইক দেওয়া', 'issue formal warnings and policy strikes to sellers', 'বিক্রেতাদের আনুষ্ঠানিক সতর্কতা ও পলিসি স্ট্রাইক দিতে', 'MEDIUM', true, 'approve_before'),
  ('users.account.suspend', 'users', 'Suspend accounts', 'অ্যাকাউন্ট স্থগিত করা', 'suspend a user''s account and block them from trading', 'কোনো ইউজারের অ্যাকাউন্ট স্থগিত করে তার লেনদেন বন্ধ করতে', 'HIGH', true, 'approve_before'),
  ('users.account.delete', 'users', 'Delete accounts', 'অ্যাকাউন্ট মুছে ফেলা', 'permanently delete a user account', 'কোনো ইউজার অ্যাকাউন্ট স্থায়ীভাবে মুছে ফেলতে', 'CRITICAL', false, 'approve_before'),
  ('users.account.impersonate', 'users', 'Sign in as another user', 'অন্য ইউজার হিসেবে লগইন', 'sign in as another user to reproduce their problem', 'সমস্যা যাচাই করতে অন্য ইউজার হিসেবে লগইন করতে', 'CRITICAL', false, 'approve_before'),
  ('users.kyc.view', 'users', 'View KYC submissions', 'কেওয়াইসি আবেদন দেখা', 'open the verification queue and read submissions', 'ভেরিফিকেশন সারি খুলে আবেদনগুলো পড়তে', 'MEDIUM', true, 'approve_before'),
  ('users.kyc.document_view', 'users', 'Open KYC documents', 'কেওয়াইসি নথি খোলা', 'open the actual NID and trade licence images', 'আসল এনআইডি ও ট্রেড লাইসেন্সের ছবি খুলতে', 'HIGH', true, 'approve_before'),
  ('users.kyc.approve', 'users', 'Approve verification', 'ভেরিফিকেশন অনুমোদন', 'approve a seller''s identity verification and issue the blue tick', 'বিক্রেতার পরিচয় ভেরিফিকেশন অনুমোদন করে ব্লু-টিক দিতে', 'HIGH', true, 'approve_before'),
  ('users.kyc.reject', 'users', 'Reject verification', 'ভেরিফিকেশন বাতিল', 'reject a verification submission with a reason', 'কারণসহ ভেরিফিকেশন আবেদন বাতিল করতে', 'HIGH', true, 'approve_before'),
  ('users.restriction.view', 'users', 'View account restrictions', 'অ্যাকাউন্ট নিষেধাজ্ঞা দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('users.restriction.manage', 'users', 'Apply account restrictions', 'অ্যাকাউন্ট নিষেধাজ্ঞা প্রয়োগ', 'block or limit what a user can do — selling, buying, withdrawing, chatting', 'কোনো ইউজারের বিক্রি, কেনা, টাকা তোলা বা চ্যাট বন্ধ বা সীমিত করতে', 'HIGH', true, 'approve_before'),
  ('users.permission.grant', 'users', 'Grant permissions', 'অনুমতি প্রদান', 'give another staff member access to a platform capability', 'অন্য স্টাফ সদস্যকে কোনো প্ল্যাটফর্ম ক্ষমতার অ্যাক্সেস দিতে', 'CRITICAL', false, 'approve_before'),
  ('users.permission.revoke', 'users', 'Revoke permissions', 'অনুমতি প্রত্যাহার', 'take back access previously granted to a staff member', 'স্টাফ সদস্যকে আগে দেওয়া অ্যাক্সেস ফিরিয়ে নিতে', 'CRITICAL', false, 'approve_before'),
  ('users.trust.adjust', 'users', 'Adjust trust score', 'ট্রাস্ট স্কোর সমন্বয়', 'manually change a customer''s COD trust score', 'কোনো ক্রেতার ক্যাশ-অন-ডেলিভারি ট্রাস্ট স্কোর হাতে পরিবর্তন করতে', 'HIGH', true, 'approve_before'),
  ('users.tier.override', 'users', 'Override seller tier', 'বিক্রেতার টিয়ার পরিবর্তন', 'manually promote or demote a seller''s trust tier', 'কোনো বিক্রেতার ট্রাস্ট টিয়ার হাতে বাড়াতে বা কমাতে', 'HIGH', true, 'approve_before'),
  ('staff.account.view', 'staff', 'View staff accounts', 'স্টাফ অ্যাকাউন্ট দেখা', 'see the list of admins, moderators and editors', 'অ্যাডমিন, মডারেটর ও এডিটরদের তালিকা দেখতে', 'MEDIUM', true, 'approve_before'),
  ('staff.account.create', 'staff', 'Create staff accounts', 'স্টাফ অ্যাকাউন্ট তৈরি', 'invite a new admin, moderator or editor', 'নতুন অ্যাডমিন, মডারেটর বা এডিটর যুক্ত করতে', 'CRITICAL', false, 'approve_before'),
  ('staff.account.disable', 'staff', 'Disable staff accounts', 'স্টাফ অ্যাকাউন্ট নিষ্ক্রিয়', 'disable a staff member''s access entirely', 'কোনো স্টাফ সদস্যের অ্যাক্সেস সম্পূর্ণ বন্ধ করতে', 'CRITICAL', false, 'approve_before'),
  ('staff.role.assign', 'staff', 'Assign roles', 'রোল নির্ধারণ', 'change which role a staff member holds', 'কোনো স্টাফ সদস্যের রোল পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('staff.role.create', 'staff', 'Create roles', 'রোল তৈরি', 'create a new staff role with its own permission set', 'নিজস্ব অনুমতিসহ নতুন স্টাফ রোল তৈরি করতে', 'CRITICAL', false, 'approve_before'),
  ('staff.role.edit', 'staff', 'Edit role permissions', 'রোলের অনুমতি সম্পাদনা', 'change which permissions a role includes', 'কোনো রোলে কোন অনুমতিগুলো থাকবে তা পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('admin.dashboard.view', 'admin', 'View admin dashboard', 'অ্যাডমিন ড্যাশবোর্ড দেখা', 'open the executive dashboard with platform-wide figures', 'পুরো প্ল্যাটফর্মের হিসাবসহ এক্সিকিউটিভ ড্যাশবোর্ড খুলতে', 'MEDIUM', true, 'approve_before'),
  ('admin.approval.view', 'admin', 'View approval inbox', 'অনুমোদন ইনবক্স দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('admin.approval.decide', 'admin', 'Approve or reject pending actions', 'অপেক্ষমাণ কাজ অনুমোদন বা বাতিল', 'approve or reject actions and access requests submitted by staff', 'স্টাফদের জমা দেওয়া কাজ ও অ্যাক্সেস আবেদন অনুমোদন বা বাতিল করতে', 'HIGH', true, 'approve_before'),
  ('admin.analytics.view', 'admin', 'View platform analytics', 'প্ল্যাটফর্ম অ্যানালিটিক্স দেখা', 'see GMV, revenue and growth reports', 'জিএমভি, রাজস্ব ও প্রবৃদ্ধির রিপোর্ট দেখতে', 'MEDIUM', true, 'approve_before'),
  ('admin.analytics.export', 'admin', 'Export analytics data', 'অ্যানালিটিক্স ডেটা এক্সপোর্ট', 'download platform data as CSV', 'প্ল্যাটফর্মের ডেটা সিএসভি হিসেবে ডাউনলোড করতে', 'HIGH', true, 'approve_before'),
  ('security.audit.view', 'security', 'View audit log', 'অডিট লগ দেখা', 'see the full record of who did what on the platform', 'প্ল্যাটফর্মে কে কী করেছে তার সম্পূর্ণ রেকর্ড দেখতে', 'MEDIUM', true, 'approve_before'),
  ('security.audit.verify', 'security', 'Verify audit chain', 'অডিট চেইন যাচাই', 'run the tamper-evidence check on the audit log', 'অডিট লগে কারচুপি হয়েছে কিনা তা যাচাই করতে', 'MEDIUM', true, 'approve_before'),
  ('security.audit.export', 'security', 'Export audit log', 'অডিট লগ এক্সপোর্ট', 'download the audit log as a file', 'অডিট লগ ফাইল হিসেবে ডাউনলোড করতে', 'HIGH', true, 'approve_before'),
  ('security.session.view', 'security', 'View active sessions', 'সক্রিয় সেশন দেখা', 'see which devices are currently signed in', 'কোন কোন ডিভাইস এখন লগইন আছে তা দেখতে', 'MEDIUM', true, 'approve_before'),
  ('security.session.revoke', 'security', 'Force sign-out', 'জোরপূর্বক লগআউট', 'sign a user out of all their devices immediately', 'কোনো ইউজারকে সব ডিভাইস থেকে সঙ্গে সঙ্গে লগআউট করতে', 'HIGH', true, 'execute_then_review'),
  ('security.2fa.reset', 'security', 'Reset a user''s 2FA', 'টু-ফ্যাক্টর রিসেট', 'reset two-factor authentication for a locked-out staff member', 'আটকে যাওয়া স্টাফ সদস্যের টু-ফ্যাক্টর অথেনটিকেশন রিসেট করতে', 'HIGH', true, 'approve_before'),
  ('security.2fa.manage', 'security', 'Configure 2FA policy', 'টু-ফ্যাক্টর নীতি নির্ধারণ', 'change which staff are required to use two-factor authentication', 'কোন স্টাফদের টু-ফ্যাক্টর বাধ্যতামূলক তা পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('security.ip.manage', 'security', 'Manage admin IP allowlist', 'অ্যাডমিন আইপি অনুমোদন তালিকা', 'change which networks can reach the admin panel', 'কোন নেটওয়ার্ক থেকে অ্যাডমিন প্যানেলে ঢোকা যাবে তা নির্ধারণ করতে', 'CRITICAL', false, 'approve_before'),
  ('security.breakglass.use', 'security', 'Emergency break-glass access', 'জরুরি ব্রেক-গ্লাস অ্যাক্সেস', 'bypass normal controls during an emergency — heavily audited and alerted', 'জরুরি অবস্থায় স্বাভাবিক নিয়ন্ত্রণ এড়াতে — সম্পূর্ণ অডিট ও সতর্কতাসহ', 'CRITICAL', false, 'approve_before'),
  ('system.health.view', 'system', 'View system health', 'সিস্টেম হেলথ দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('system.job.view', 'system', 'View background jobs', 'ব্যাকগ্রাউন্ড জব দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('system.job.retrigger', 'system', 'Re-run a background job', 'ব্যাকগ্রাউন্ড জব পুনরায় চালানো', 'manually re-run a scheduled job such as escrow release', 'এসক্রো রিলিজের মতো নির্ধারিত জব হাতে আবার চালাতে', 'HIGH', true, 'approve_before'),
  ('system.backup.trigger', 'system', 'Trigger a backup', 'ব্যাকআপ চালু করা', 'take an immediate database snapshot', 'এখনই ডেটাবেসের একটি স্ন্যাপশট নিতে', 'HIGH', true, 'approve_before'),
  ('system.backup.manage', 'system', 'Manage backup policy', 'ব্যাকআপ নীতি ব্যবস্থাপনা', 'change backup schedules and retention', 'ব্যাকআপের সময়সূচি ও সংরক্ষণকাল পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('system.backup.restore', 'system', 'Restore from backup', 'ব্যাকআপ থেকে পুনরুদ্ধার', 'restore the database from a snapshot — overwrites live data', 'স্ন্যাপশট থেকে ডেটাবেস পুনরুদ্ধার করতে — চলমান ডেটা মুছে যাবে', 'CRITICAL', false, 'approve_before'),
  ('platform.module.view', 'platform', 'View module settings', 'মডিউল সেটিংস দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('platform.module.toggle', 'platform', 'Turn modules on or off', 'মডিউল চালু বা বন্ধ করা', 'enable or disable any platform feature for everyone', 'সবার জন্য যেকোনো প্ল্যাটফর্ম ফিচার চালু বা বন্ধ করতে', 'CRITICAL', false, 'approve_before'),
  ('platform.module.settings', 'platform', 'Change module settings', 'মডিউল সেটিংস পরিবর্তন', 'change a module''s configuration, such as the return window', 'কোনো মডিউলের কনফিগারেশন যেমন রিটার্ন সময়সীমা পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('platform.module.targeting', 'platform', 'Configure module targeting', 'মডিউল টার্গেটিং নির্ধারণ', 'control which roles, districts or users a module applies to', 'কোন রোল, জেলা বা ইউজারের জন্য মডিউলটি প্রযোজ্য তা নিয়ন্ত্রণ করতে', 'CRITICAL', false, 'approve_before'),
  ('platform.theme.view', 'platform', 'View theme studio', 'থিম স্টুডিও দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('platform.theme.draft', 'platform', 'Draft a theme', 'থিম খসড়া তৈরি', 'create and preview a colour palette without publishing it', 'প্রকাশ না করে রঙের প্যালেট তৈরি ও প্রিভিউ করতে', 'MEDIUM', true, 'approve_before'),
  ('platform.theme.publish', 'platform', 'Publish a theme', 'থিম প্রকাশ', 'change the site''s colours for every visitor', 'সব দর্শনার্থীর জন্য সাইটের রঙ পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('platform.settings.view', 'platform', 'View platform settings', 'প্ল্যাটফর্ম সেটিংস দেখা', 'see global configuration values', 'গ্লোবাল কনফিগারেশন মান দেখতে', 'MEDIUM', true, 'approve_before'),
  ('platform.settings.update', 'platform', 'Change platform settings', 'প্ল্যাটফর্ম সেটিংস পরিবর্তন', 'change global configuration such as minimum payout or escrow period', 'সর্বনিম্ন পেআউট বা এসক্রো সময়ের মতো গ্লোবাল কনফিগারেশন পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('platform.integration.view', 'platform', 'View integrations', 'ইন্টিগ্রেশন দেখা', 'see which payment and courier integrations are connected', 'কোন পেমেন্ট ও কুরিয়ার ইন্টিগ্রেশন যুক্ত আছে তা দেখতে', 'MEDIUM', true, 'approve_before'),
  ('platform.integration.manage', 'platform', 'Manage integration credentials', 'ইন্টিগ্রেশন ক্রেডেনশিয়াল ব্যবস্থাপনা', 'change bKash, Nagad, courier and SMS gateway credentials', 'বিকাশ, নগদ, কুরিয়ার ও এসএমএস গেটওয়ের ক্রেডেনশিয়াল পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('platform.apikey.view', 'platform', 'View API keys', 'এপিআই কী দেখা', 'see which third-party developers have API access', 'কোন থার্ড-পার্টি ডেভেলপারের এপিআই অ্যাক্সেস আছে তা দেখতে', 'MEDIUM', true, 'approve_before'),
  ('platform.apikey.manage', 'platform', 'Manage API keys', 'এপিআই কী ব্যবস্থাপনা', 'issue, rotate or revoke developer API keys', 'ডেভেলপার এপিআই কী তৈরি, পরিবর্তন বা বাতিল করতে', 'CRITICAL', false, 'approve_before'),
  ('platform.webhook.manage', 'platform', 'Manage outbound webhooks', 'আউটবাউন্ড ওয়েবহুক ব্যবস্থাপনা', 'configure and replay outgoing webhook deliveries', 'আউটগোয়িং ওয়েবহুক কনফিগার ও পুনরায় পাঠাতে', 'HIGH', true, 'approve_before'),
  ('catalog.product.create', 'catalog', 'Create products', 'পণ্য তৈরি', NULL, NULL, 'LOW', true, 'approve_before'),
  ('catalog.product.manage_own', 'catalog', 'Manage own products', 'নিজের পণ্য ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('catalog.product.view_all', 'catalog', 'View all products', 'সব পণ্য দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('catalog.product.edit_any', 'catalog', 'Edit any product', 'যেকোনো পণ্য সম্পাদনা', 'edit a product listing that belongs to another seller', 'অন্য বিক্রেতার পণ্যের তালিকা সম্পাদনা করতে', 'HIGH', true, 'approve_before'),
  ('catalog.product.delete', 'catalog', 'Delete products', 'পণ্য মুছে ফেলা', 'remove a product listing from the marketplace', 'মার্কেটপ্লেস থেকে কোনো পণ্য সরিয়ে ফেলতে', 'HIGH', true, 'approve_before'),
  ('catalog.product.feature', 'catalog', 'Feature products', 'পণ্য ফিচার করা', 'place a product on the homepage or a featured collection', 'কোনো পণ্য হোমপেজ বা ফিচার্ড কালেকশনে রাখতে', 'MEDIUM', true, 'approve_before'),
  ('catalog.category.view', 'catalog', 'View categories', 'ক্যাটেগরি দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('catalog.category.manage', 'catalog', 'Manage categories', 'ক্যাটেগরি ব্যবস্থাপনা', 'add, rename or restructure product categories', 'পণ্যের ক্যাটেগরি যোগ, নাম পরিবর্তন বা পুনর্বিন্যাস করতে', 'MEDIUM', true, 'approve_before'),
  ('catalog.inventory.manage', 'catalog', 'Manage own stock', 'নিজের স্টক ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('catalog.inventory.adjust_any', 'catalog', 'Adjust any seller''s stock', 'যেকোনো বিক্রেতার স্টক সমন্বয়', 'manually change stock levels for another seller''s product', 'অন্য বিক্রেতার পণ্যের স্টক হাতে পরিবর্তন করতে', 'HIGH', true, 'approve_before'),
  ('catalog.batch.manage', 'catalog', 'Manage own batches', 'নিজের ব্যাচ ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('catalog.batch.govern', 'catalog', 'Govern batch and expiry rules', 'ব্যাচ ও মেয়াদ নীতি নিয়ন্ত্রণ', 'set FEFO and expiry rules per category', 'ক্যাটেগরি অনুযায়ী ফিফো ও মেয়াদের নিয়ম নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('catalog.batch.recall', 'catalog', 'Execute a batch recall', 'ব্যাচ রিকল কার্যকর', 'freeze and recall an entire product batch across the platform', 'পুরো প্ল্যাটফর্ম জুড়ে কোনো পণ্য ব্যাচ বন্ধ ও ফেরত আনতে', 'CRITICAL', false, 'approve_before'),
  ('catalog.warehouse.manage', 'catalog', 'Manage own warehouses', 'নিজের গুদাম ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('catalog.warehouse.govern', 'catalog', 'Govern warehouse routing', 'গুদাম রাউটিং নিয়ন্ত্রণ', 'set the rules that decide which warehouse fulfils an order', 'কোন গুদাম থেকে অর্ডার পাঠানো হবে তার নিয়ম নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('moderation.dashboard.view', 'moderation', 'View moderation dashboard', 'মডারেশন ড্যাশবোর্ড দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('moderation.product.view', 'moderation', 'View moderation queue', 'মডারেশন সারি দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('moderation.product.approve', 'moderation', 'Approve product listings', 'পণ্যের তালিকা অনুমোদন', NULL, NULL, 'LOW', true, 'approve_before'),
  ('moderation.product.reject', 'moderation', 'Reject product listings', 'পণ্যের তালিকা বাতিল', NULL, NULL, 'LOW', true, 'approve_before'),
  ('moderation.product.auto_approve_config', 'moderation', 'Configure auto-approval', 'স্বয়ংক্রিয় অনুমোদন কনফিগার', 'let products in a category go live without human review', 'কোনো ক্যাটেগরির পণ্য মানুষের পর্যালোচনা ছাড়াই প্রকাশ করতে', 'CRITICAL', false, 'approve_before'),
  ('moderation.review.handle', 'moderation', 'Moderate reviews', 'রিভিউ মডারেশন', NULL, NULL, 'LOW', true, 'approve_before'),
  ('moderation.review.delete', 'moderation', 'Delete reviews', 'রিভিউ মুছে ফেলা', 'permanently remove a customer review', 'কোনো ক্রেতার রিভিউ স্থায়ীভাবে মুছে ফেলতে', 'MEDIUM', true, 'approve_before'),
  ('moderation.ugc.approve', 'moderation', 'Approve user videos', 'ইউজার ভিডিও অনুমোদন', NULL, NULL, 'LOW', true, 'approve_before'),
  ('moderation.live.handle', 'moderation', 'Moderate live streams', 'লাইভ স্ট্রিম মডারেশন', 'mute participants and remove comments during a live stream', 'লাইভ স্ট্রিম চলাকালীন অংশগ্রহণকারীদের মিউট ও মন্তব্য সরাতে', 'MEDIUM', true, 'execute_then_review'),
  ('moderation.report.view', 'moderation', 'View user reports', 'ইউজার রিপোর্ট দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('moderation.report.handle', 'moderation', 'Resolve user reports', 'ইউজার রিপোর্ট নিষ্পত্তি', NULL, NULL, 'LOW', true, 'approve_before'),
  ('moderation.queue.assign', 'moderation', 'Assign queue items', 'সারির কাজ বণ্টন', NULL, NULL, 'LOW', true, 'approve_before'),
  ('orders.order.view_own', 'orders', 'View own orders', 'নিজের অর্ডার দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('orders.order.view_all', 'orders', 'View all orders', 'সব অর্ডার দেখা', 'see every order on the platform, including other people''s', 'অন্যদেরসহ প্ল্যাটফর্মের সব অর্ডার দেখতে', 'MEDIUM', true, 'approve_before'),
  ('orders.order.cancel', 'orders', 'Cancel orders', 'অর্ডার বাতিল', 'cancel a customer''s order on their behalf', 'কোনো ক্রেতার পক্ষে তার অর্ডার বাতিল করতে', 'MEDIUM', true, 'approve_before'),
  ('orders.order.edit', 'orders', 'Edit orders', 'অর্ডার সম্পাদনা', 'change the contents or amount of a placed order', 'দেওয়া অর্ডারের পণ্য বা টাকার পরিমাণ পরিবর্তন করতে', 'HIGH', true, 'approve_before'),
  ('orders.return.request', 'orders', 'Request a return', 'রিটার্নের আবেদন', NULL, NULL, 'LOW', true, 'approve_before'),
  ('orders.return.view_all', 'orders', 'View all returns', 'সব রিটার্ন দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('orders.return.review', 'orders', 'Review return requests', 'রিটার্ন আবেদন পর্যালোচনা', 'inspect return requests and their evidence', 'রিটার্নের আবেদন ও প্রমাণ যাচাই করতে', 'MEDIUM', true, 'approve_before'),
  ('orders.return.approve', 'orders', 'Approve returns', 'রিটার্ন অনুমোদন', 'approve a return so the refund process begins', 'রিটার্ন অনুমোদন করে রিফান্ড প্রক্রিয়া শুরু করতে', 'MEDIUM', true, 'approve_before'),
  ('orders.refund.execute', 'orders', 'Execute refunds', 'রিফান্ড কার্যকর', 'send money back to a customer', 'কোনো ক্রেতাকে টাকা ফেরত পাঠাতে', 'HIGH', true, 'approve_before'),
  ('orders.refund.execute_large', 'orders', 'Execute large refunds', 'বড় অঙ্কের রিফান্ড কার্যকর', 'refund amounts above the platform''s high-value threshold', 'প্ল্যাটফর্মের উচ্চ-মূল্য সীমার উপরে রিফান্ড করতে', 'CRITICAL', false, 'approve_before'),
  ('orders.dispute.view_all', 'orders', 'View disputes', 'বিরোধ দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('orders.dispute.arbitrate', 'orders', 'Decide disputes', 'বিরোধ নিষ্পত্তি', 'decide a dispute between buyer, saler and supplier, and move money accordingly', 'ক্রেতা, সেলার ও সরবরাহকারীর মধ্যে বিরোধ নিষ্পত্তি করে সেই অনুযায়ী টাকা সরাতে', 'HIGH', true, 'approve_before'),
  ('orders.dispute.escalate', 'orders', 'Escalate a dispute', 'বিরোধ উর্ধ্বতনের কাছে পাঠানো', NULL, NULL, 'LOW', true, 'approve_before'),
  ('orders.cod.view', 'orders', 'View COD reconciliation', 'সিওডি হিসাব মিলানো দেখা', 'see cash-on-delivery collections and any discrepancies', 'ক্যাশ-অন-ডেলিভারির আদায় ও গরমিল দেখতে', 'MEDIUM', true, 'approve_before'),
  ('orders.cod.reconcile', 'orders', 'Reconcile COD settlements', 'সিওডি নিষ্পত্তি মিলানো', 'match courier cash reports against platform records', 'কুরিয়ারের নগদ রিপোর্টের সাথে প্ল্যাটফর্মের হিসাব মিলাতে', 'HIGH', true, 'approve_before'),
  ('orders.cod.resolve_discrepancy', 'orders', 'Resolve COD discrepancies', 'সিওডি গরমিল নিষ্পত্তি', 'decide how a cash shortfall or overage is settled', 'নগদ কম বা বেশি হলে তা কীভাবে নিষ্পত্তি হবে তা ঠিক করতে', 'HIGH', true, 'approve_before'),
  ('logistics.shipment.view', 'logistics', 'View shipments', 'চালান দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('logistics.consignment.create', 'logistics', 'Create consignments', 'কনসাইনমেন্ট তৈরি', NULL, NULL, 'LOW', true, 'approve_before'),
  ('logistics.consignment.cancel', 'logistics', 'Cancel consignments', 'কনসাইনমেন্ট বাতিল', 'cancel a booked courier pickup', 'বুক করা কুরিয়ার পিকআপ বাতিল করতে', 'MEDIUM', true, 'approve_before'),
  ('logistics.carrier.view', 'logistics', 'View courier hub', 'কুরিয়ার হাব দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('logistics.carrier.manage', 'logistics', 'Manage courier routing', 'কুরিয়ার রাউটিং ব্যবস্থাপনা', 'choose which courier serves which district', 'কোন জেলায় কোন কুরিয়ার সেবা দেবে তা নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('logistics.carrier.credentials', 'logistics', 'Manage courier credentials', 'কুরিয়ার ক্রেডেনশিয়াল ব্যবস্থাপনা', 'change Steadfast, Pathao and RedX API credentials', 'স্টেডফাস্ট, পাঠাও ও রেডএক্সের এপিআই ক্রেডেনশিয়াল পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('logistics.routing.configure', 'logistics', 'Configure delivery routing', 'ডেলিভারি রাউটিং কনফিগার', 'set distance thresholds and split-order rules', 'দূরত্বের সীমা ও অর্ডার ভাগের নিয়ম নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('finance.wallet.view_own', 'finance', 'View own wallet', 'নিজের ওয়ালেট দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('finance.wallet.view_any', 'finance', 'View any wallet', 'যেকোনো ওয়ালেট দেখা', 'see another user''s balance and transaction history', 'অন্য ইউজারের ব্যালেন্স ও লেনদেনের ইতিহাস দেখতে', 'MEDIUM', true, 'approve_before'),
  ('finance.wallet.adjust', 'finance', 'Manually adjust a wallet', 'ওয়ালেট হাতে সমন্বয়', 'add or remove money from a user''s wallet directly', 'কোনো ইউজারের ওয়ালেটে সরাসরি টাকা যোগ বা বিয়োগ করতে', 'CRITICAL', false, 'approve_before'),
  ('finance.overview.view', 'finance', 'View finance overview', 'আর্থিক সারসংক্ষেপ দেখা', 'see platform revenue, liability and exposure figures', 'প্ল্যাটফর্মের রাজস্ব, দায় ও ঝুঁকির হিসাব দেখতে', 'MEDIUM', true, 'approve_before'),
  ('finance.ledger.view', 'finance', 'View the ledger', 'লেজার দেখা', 'open the double-entry accounting ledger', 'ডাবল-এন্ট্রি হিসাবের লেজার খুলতে', 'MEDIUM', true, 'approve_before'),
  ('finance.ledger.export', 'finance', 'Export the ledger', 'লেজার এক্সপোর্ট', 'download full financial records as a file', 'সম্পূর্ণ আর্থিক রেকর্ড ফাইল হিসেবে ডাউনলোড করতে', 'HIGH', true, 'approve_before'),
  ('finance.integrity.check', 'finance', 'Run ledger integrity check', 'লেজার সঠিকতা যাচাই', 'verify that every wallet balance matches the ledger', 'প্রতিটি ওয়ালেটের ব্যালেন্স লেজারের সাথে মেলে কিনা যাচাই করতে', 'MEDIUM', true, 'approve_before'),
  ('finance.escrow.view', 'finance', 'View escrow holdings', 'এসক্রো জমা দেখা', 'see money held in the return-window escrow', 'রিটার্ন সময়সীমার এসক্রোতে আটকে থাকা টাকা দেখতে', 'MEDIUM', true, 'approve_before'),
  ('finance.escrow.freeze', 'finance', 'Freeze escrow', 'এসক্রো জব্দ', 'hold escrowed money past its normal release date', 'স্বাভাবিক ছাড়ের তারিখের পরেও এসক্রোর টাকা আটকে রাখতে', 'HIGH', true, 'execute_then_review'),
  ('finance.escrow.release_manual', 'finance', 'Manually release escrow', 'এসক্রো হাতে ছাড়', 'release escrowed money before the return window ends', 'রিটার্ন সময়সীমা শেষ হওয়ার আগেই এসক্রোর টাকা ছেড়ে দিতে', 'CRITICAL', false, 'approve_before'),
  ('finance.payout.request', 'finance', 'Request a payout', 'পেআউটের আবেদন', NULL, NULL, 'LOW', true, 'approve_before'),
  ('finance.payout.view', 'finance', 'View payout queue', 'পেআউট সারি দেখা', 'see pending withdrawal requests', 'অপেক্ষমাণ উত্তোলনের আবেদনগুলো দেখতে', 'MEDIUM', true, 'approve_before'),
  ('finance.payout.reject', 'finance', 'Reject payouts', 'পেআউট বাতিল', 'decline a withdrawal request with a reason', 'কারণসহ কোনো উত্তোলনের আবেদন বাতিল করতে', 'MEDIUM', true, 'approve_before'),
  ('finance.payout.approve', 'finance', 'Approve payouts', 'পেআউট অনুমোদন', 'approve withdrawal requests and send money to sellers', 'উত্তোলনের আবেদন অনুমোদন করে বিক্রেতাদের টাকা পাঠাতে', 'HIGH', true, 'approve_before'),
  ('finance.payout.approve_large', 'finance', 'Approve large payouts', 'বড় অঙ্কের পেআউট অনুমোদন', 'approve withdrawals above the platform''s high-value threshold', 'প্ল্যাটফর্মের উচ্চ-মূল্য সীমার উপরে উত্তোলন অনুমোদন করতে', 'CRITICAL', false, 'approve_before'),
  ('finance.payout.batch', 'finance', 'Batch-disburse payouts', 'একসাথে পেআউট পাঠানো', 'pay out many approved withdrawals at once', 'একসাথে অনেক অনুমোদিত উত্তোলন পাঠাতে', 'HIGH', true, 'approve_before'),
  ('finance.split.view', 'finance', 'View profit splits', 'মুনাফা বণ্টন দেখা', 'see the commission split rules', 'কমিশন বণ্টনের নিয়ম দেখতে', 'MEDIUM', true, 'approve_before'),
  ('finance.split.update', 'finance', 'Change profit splits', 'মুনাফা বণ্টন পরিবর্তন', 'change how commission is divided between saler and platform', 'সেলার ও প্ল্যাটফর্মের মধ্যে কমিশন কীভাবে ভাগ হবে তা পরিবর্তন করতে', 'CRITICAL', false, 'approve_before'),
  ('finance.subscription.manage', 'finance', 'Manage seller fees', 'বিক্রেতা ফি ব্যবস্থাপনা', 'turn on or configure seller subscription and listing fees', 'বিক্রেতার সাবস্ক্রিপশন ও লিস্টিং ফি চালু বা নির্ধারণ করতে', 'CRITICAL', false, 'approve_before'),
  ('finance.clawback.execute', 'finance', 'Execute a clawback', 'ক্লব্যাক কার্যকর', 'reverse a commission already credited to a seller', 'বিক্রেতাকে আগে দেওয়া কমিশন ফিরিয়ে নিতে', 'HIGH', true, 'approve_before'),
  ('finance.b2b_escrow.view_own', 'finance', 'View own B2B escrow', 'নিজের বি২বি এসক্রো দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('finance.b2b_escrow.manage', 'finance', 'Manage B2B escrow', 'বি২বি এসক্রো ব্যবস্থাপনা', 'oversee wholesale escrow deals and their milestones', 'পাইকারি এসক্রো চুক্তি ও তার ধাপগুলো তদারকি করতে', 'HIGH', true, 'approve_before'),
  ('finance.b2b_escrow.release', 'finance', 'Release B2B milestone funds', 'বি২বি ধাপের টাকা ছাড়', 'manually release a wholesale escrow milestone payment', 'পাইকারি এসক্রোর কোনো ধাপের টাকা হাতে ছেড়ে দিতে', 'CRITICAL', false, 'approve_before'),
  ('growth.ad.manage_own', 'growth', 'Manage own ad campaigns', 'নিজের বিজ্ঞাপন ক্যাম্পেইন', NULL, NULL, 'LOW', true, 'approve_before'),
  ('growth.ad.review', 'growth', 'Review ad creatives', 'বিজ্ঞাপন পর্যালোচনা', 'approve or reject seller advertisements before they run', 'বিক্রেতার বিজ্ঞাপন চালুর আগে অনুমোদন বা বাতিল করতে', 'MEDIUM', true, 'approve_before'),
  ('growth.ad.govern', 'growth', 'Govern the ads engine', 'বিজ্ঞাপন ইঞ্জিন নিয়ন্ত্রণ', 'set ad density caps, blocked keywords and auction rules', 'বিজ্ঞাপনের সীমা, নিষিদ্ধ শব্দ ও নিলামের নিয়ম নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('growth.coupon.create_own', 'growth', 'Create own coupons', 'নিজের কুপন তৈরি', NULL, NULL, 'LOW', true, 'approve_before'),
  ('growth.coupon.manage', 'growth', 'Manage coupons', 'কুপন ব্যবস্থাপনা', 'view and edit coupons created by sellers', 'বিক্রেতাদের তৈরি কুপন দেখা ও সম্পাদনা করতে', 'MEDIUM', true, 'approve_before'),
  ('growth.coupon.platform_wide', 'growth', 'Create platform-wide coupons', 'প্ল্যাটফর্ম-ব্যাপী কুপন তৈরি', 'create a discount funded by the platform and valid everywhere', 'প্ল্যাটফর্মের খরচে সব জায়গায় চলবে এমন ছাড় তৈরি করতে', 'HIGH', true, 'approve_before'),
  ('growth.campaign.manage', 'growth', 'Manage campaigns', 'ক্যাম্পেইন ব্যবস্থাপনা', 'create and schedule flash sales and seasonal campaigns', 'ফ্ল্যাশ সেল ও মৌসুমি ক্যাম্পেইন তৈরি ও সময় নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('growth.campaign.emergency_stop', 'growth', 'Emergency-stop a campaign', 'ক্যাম্পেইন জরুরি বন্ধ', 'immediately halt a running campaign that is losing money', 'লোকসান হচ্ছে এমন চলমান ক্যাম্পেইন সঙ্গে সঙ্গে বন্ধ করতে', 'HIGH', true, 'execute_then_review'),
  ('growth.referral.view_own', 'growth', 'View own referrals', 'নিজের রেফারেল দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('growth.referral.govern', 'growth', 'Govern referral rules', 'রেফারেল নীতি নিয়ন্ত্রণ', 'set referral commission rates and payout conditions', 'রেফারেল কমিশনের হার ও শর্ত নির্ধারণ করতে', 'CRITICAL', false, 'approve_before'),
  ('growth.coins.view_own', 'growth', 'View own coins', 'নিজের কয়েন দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('growth.coins.adjust', 'growth', 'Adjust a user''s coins', 'ইউজারের কয়েন সমন্বয়', 'add or remove loyalty coins from a user''s balance', 'কোনো ইউজারের লয়ালটি কয়েন যোগ বা বিয়োগ করতে', 'HIGH', true, 'approve_before'),
  ('growth.coins.govern', 'growth', 'Govern coin policy', 'কয়েন নীতি নিয়ন্ত্রণ', 'set coin earning rates and redemption value', 'কয়েন আয়ের হার ও ব্যবহারের মূল্য নির্ধারণ করতে', 'CRITICAL', false, 'approve_before'),
  ('growth.quest.govern', 'growth', 'Govern quests and rewards', 'কোয়েস্ট ও পুরস্কার নিয়ন্ত্রণ', 'create daily missions and set their reward amounts', 'দৈনিক মিশন তৈরি ও তার পুরস্কার নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('growth.leaderboard.govern', 'growth', 'Govern the leaderboard', 'লিডারবোর্ড নিয়ন্ত্রণ', 'configure the monthly bonus pool and ranking rules', 'মাসিক বোনাস পুল ও র‍্যাংকিংয়ের নিয়ম নির্ধারণ করতে', 'MEDIUM', true, 'approve_before'),
  ('growth.groupbuy.govern', 'growth', 'Govern group buying', 'গ্রুপ কেনাকাটা নিয়ন্ত্রণ', 'set team sizes, time limits and minimum discounts', 'দলের আকার, সময়সীমা ও সর্বনিম্ন ছাড় নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('content.dashboard.view', 'content', 'View content dashboard', 'কনটেন্ট ড্যাশবোর্ড দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('content.banner.publish', 'content', 'Publish homepage banners', 'হোমপেজ ব্যানার প্রকাশ', NULL, NULL, 'LOW', true, 'approve_before'),
  ('content.story.curate', 'content', 'Curate stories', 'স্টোরি কিউরেট করা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('content.story.publish_own', 'content', 'Publish own stories', 'নিজের স্টোরি প্রকাশ', NULL, NULL, 'LOW', true, 'approve_before'),
  ('content.academy.manage', 'content', 'Manage Seller Academy', 'সেলার একাডেমি ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('content.announcement.publish', 'content', 'Publish announcements', 'ঘোষণা প্রকাশ', 'publish a What''s New popup shown to every user', 'সব ইউজারকে দেখানো হবে এমন নতুন-কী পপআপ প্রকাশ করতে', 'MEDIUM', true, 'approve_before'),
  ('content.i18n.update', 'content', 'Edit translations', 'অনুবাদ সম্পাদনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('content.i18n.locale_add', 'content', 'Add a language', 'নতুন ভাষা যোগ', 'add a new language to the platform', 'প্ল্যাটফর্মে নতুন একটি ভাষা যোগ করতে', 'HIGH', true, 'approve_before'),
  ('content.help.manage', 'content', 'Manage help centre', 'হেল্প সেন্টার ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('chat.thread.view_own', 'chat', 'View own conversations', 'নিজের কথোপকথন দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('chat.message.send', 'chat', 'Send messages', 'বার্তা পাঠানো', NULL, NULL, 'LOW', true, 'approve_before'),
  ('chat.thread.view_any', 'chat', 'Read any conversation', 'যেকোনো কথোপকথন পড়া', 'read private messages between other users — used only for investigating reports', 'অন্য ইউজারদের ব্যক্তিগত বার্তা পড়তে — শুধু রিপোর্ট তদন্তের জন্য', 'HIGH', true, 'approve_before'),
  ('chat.message.moderate', 'chat', 'Moderate messages', 'বার্তা মডারেশন', 'remove reported messages and warn the sender', 'রিপোর্ট হওয়া বার্তা সরিয়ে প্রেরককে সতর্ক করতে', 'MEDIUM', true, 'approve_before'),
  ('chat.broadcast.send', 'chat', 'Send a broadcast', 'ব্রডকাস্ট পাঠানো', 'send a message or notification to every user at once', 'একসাথে সব ইউজারকে বার্তা বা নোটিফিকেশন পাঠাতে', 'HIGH', true, 'approve_before'),
  ('live.stream.view', 'live', 'Watch live streams', 'লাইভ স্ট্রিম দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('live.stream.host', 'live', 'Host live streams', 'লাইভ স্ট্রিম হোস্ট করা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('live.stream.terminate', 'live', 'End someone''s live stream', 'কারো লাইভ স্ট্রিম বন্ধ করা', 'immediately end a live broadcast that violates policy', 'নীতি ভঙ্গকারী কোনো লাইভ সম্প্রচার সঙ্গে সঙ্গে বন্ধ করতে', 'HIGH', true, 'execute_then_review'),
  ('live.stream.govern', 'live', 'Govern live commerce', 'লাইভ কমার্স নিয়ন্ত্রণ', 'set bandwidth limits and who is allowed to broadcast', 'ব্যান্ডউইথ সীমা ও কারা সম্প্রচার করতে পারবে তা নির্ধারণ করতে', 'HIGH', true, 'approve_before'),
  ('support.warranty.view_own', 'support', 'View own warranties', 'নিজের ওয়ারেন্টি দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('support.warranty.claim', 'support', 'File a warranty claim', 'ওয়ারেন্টি দাবি করা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('support.warranty.manage', 'support', 'Manage warranty claims', 'ওয়ারেন্টি দাবি ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('support.warranty.override', 'support', 'Override a warranty decision', 'ওয়ারেন্টি সিদ্ধান্ত পরিবর্তন', 'overrule a supplier''s warranty claim decision', 'সরবরাহকারীর ওয়ারেন্টি সিদ্ধান্ত বাতিল করে নতুন সিদ্ধান্ত দিতে', 'HIGH', true, 'approve_before'),
  ('saler.dashboard.view', 'saler', 'View saler dashboard', 'সেলার ড্যাশবোর্ড দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('saler.store.manage', 'saler', 'Manage own storefront', 'নিজের স্টোরফ্রন্ট ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('saler.sourcing.view', 'saler', 'Browse sourcing catalog', 'সোর্সিং ক্যাটালগ দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('saler.order.view', 'saler', 'View own saler orders', 'নিজের সেলার অর্ডার দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('saler.analytics.view', 'saler', 'View own analytics', 'নিজের অ্যানালিটিক্স দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('saler.bundle.manage', 'saler', 'Manage product bundles', 'পণ্য বান্ডেল ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('supplier.dashboard.view', 'supplier', 'View supplier dashboard', 'সরবরাহকারী ড্যাশবোর্ড দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('supplier.order.view', 'supplier', 'View incoming orders', 'আসা অর্ডার দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('supplier.analytics.view', 'supplier', 'View supplier analytics', 'সরবরাহকারী অ্যানালিটিক্স দেখা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('supplier.store.manage', 'supplier', 'Manage physical shop status', 'দোকানের অবস্থা ব্যবস্থাপনা', NULL, NULL, 'LOW', true, 'approve_before'),
  ('ai.concierge.use', 'ai', 'Use the shopping assistant', 'শপিং সহকারী ব্যবহার', NULL, NULL, 'LOW', true, 'approve_before'),
  ('ai.sourcing.use', 'ai', 'Use the sourcing assistant', 'সোর্সিং সহকারী ব্যবহার', NULL, NULL, 'LOW', true, 'approve_before'),
  ('ai.creative.use', 'ai', 'Use the creative studio', 'ক্রিয়েটিভ স্টুডিও ব্যবহার', NULL, NULL, 'LOW', true, 'approve_before'),
  ('ai.config.manage', 'ai', 'Configure AI settings', 'এআই সেটিংস কনফিগার', 'change the AI model, spend cap and safety settings', 'এআই মডেল, খরচের সীমা ও নিরাপত্তা সেটিংস পরিবর্তন করতে', 'CRITICAL', false, 'approve_before')
ON CONFLICT (key) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_key)
SELECT r.id, x.permission_key
FROM (VALUES
  ('moderator', 'users.account.view'),
  ('admin', 'users.account.view'),
  ('super_admin', 'users.account.view'),
  ('admin', 'users.account.view_pii'),
  ('super_admin', 'users.account.view_pii'),
  ('admin', 'users.account.edit'),
  ('super_admin', 'users.account.edit'),
  ('moderator', 'users.account.penalise'),
  ('admin', 'users.account.penalise'),
  ('super_admin', 'users.account.penalise'),
  ('admin', 'users.account.suspend'),
  ('super_admin', 'users.account.suspend'),
  ('super_admin', 'users.account.delete'),
  ('super_admin', 'users.account.impersonate'),
  ('moderator', 'users.kyc.view'),
  ('admin', 'users.kyc.view'),
  ('super_admin', 'users.kyc.view'),
  ('admin', 'users.kyc.document_view'),
  ('super_admin', 'users.kyc.document_view'),
  ('admin', 'users.kyc.approve'),
  ('super_admin', 'users.kyc.approve'),
  ('admin', 'users.kyc.reject'),
  ('super_admin', 'users.kyc.reject'),
  ('moderator', 'users.restriction.view'),
  ('admin', 'users.restriction.view'),
  ('super_admin', 'users.restriction.view'),
  ('admin', 'users.restriction.manage'),
  ('super_admin', 'users.restriction.manage'),
  ('super_admin', 'users.permission.grant'),
  ('super_admin', 'users.permission.revoke'),
  ('admin', 'users.trust.adjust'),
  ('super_admin', 'users.trust.adjust'),
  ('admin', 'users.tier.override'),
  ('super_admin', 'users.tier.override'),
  ('admin', 'staff.account.view'),
  ('super_admin', 'staff.account.view'),
  ('super_admin', 'staff.account.create'),
  ('super_admin', 'staff.account.disable'),
  ('super_admin', 'staff.role.assign'),
  ('super_admin', 'staff.role.create'),
  ('super_admin', 'staff.role.edit'),
  ('admin', 'admin.dashboard.view'),
  ('super_admin', 'admin.dashboard.view'),
  ('admin', 'admin.approval.view'),
  ('super_admin', 'admin.approval.view'),
  ('admin', 'admin.approval.decide'),
  ('super_admin', 'admin.approval.decide'),
  ('admin', 'admin.analytics.view'),
  ('super_admin', 'admin.analytics.view'),
  ('admin', 'admin.analytics.export'),
  ('super_admin', 'admin.analytics.export'),
  ('admin', 'security.audit.view'),
  ('super_admin', 'security.audit.view'),
  ('admin', 'security.audit.verify'),
  ('super_admin', 'security.audit.verify'),
  ('super_admin', 'security.audit.export'),
  ('admin', 'security.session.view'),
  ('super_admin', 'security.session.view'),
  ('admin', 'security.session.revoke'),
  ('super_admin', 'security.session.revoke'),
  ('admin', 'security.2fa.reset'),
  ('super_admin', 'security.2fa.reset'),
  ('super_admin', 'security.2fa.manage'),
  ('super_admin', 'security.ip.manage'),
  ('super_admin', 'security.breakglass.use'),
  ('admin', 'system.health.view'),
  ('super_admin', 'system.health.view'),
  ('admin', 'system.job.view'),
  ('super_admin', 'system.job.view'),
  ('admin', 'system.job.retrigger'),
  ('super_admin', 'system.job.retrigger'),
  ('admin', 'system.backup.trigger'),
  ('super_admin', 'system.backup.trigger'),
  ('super_admin', 'system.backup.manage'),
  ('super_admin', 'system.backup.restore'),
  ('moderator', 'platform.module.view'),
  ('editor', 'platform.module.view'),
  ('admin', 'platform.module.view'),
  ('super_admin', 'platform.module.view'),
  ('super_admin', 'platform.module.toggle'),
  ('super_admin', 'platform.module.settings'),
  ('super_admin', 'platform.module.targeting'),
  ('editor', 'platform.theme.view'),
  ('admin', 'platform.theme.view'),
  ('super_admin', 'platform.theme.view'),
  ('editor', 'platform.theme.draft'),
  ('admin', 'platform.theme.draft'),
  ('super_admin', 'platform.theme.draft'),
  ('super_admin', 'platform.theme.publish'),
  ('admin', 'platform.settings.view'),
  ('super_admin', 'platform.settings.view'),
  ('super_admin', 'platform.settings.update'),
  ('admin', 'platform.integration.view'),
  ('super_admin', 'platform.integration.view'),
  ('super_admin', 'platform.integration.manage'),
  ('admin', 'platform.apikey.view'),
  ('super_admin', 'platform.apikey.view'),
  ('super_admin', 'platform.apikey.manage'),
  ('admin', 'platform.webhook.manage'),
  ('super_admin', 'platform.webhook.manage'),
  ('supplier', 'catalog.product.create'),
  ('supplier', 'catalog.product.manage_own'),
  ('moderator', 'catalog.product.view_all'),
  ('admin', 'catalog.product.view_all'),
  ('super_admin', 'catalog.product.view_all'),
  ('admin', 'catalog.product.edit_any'),
  ('super_admin', 'catalog.product.edit_any'),
  ('admin', 'catalog.product.delete'),
  ('super_admin', 'catalog.product.delete'),
  ('editor', 'catalog.product.feature'),
  ('admin', 'catalog.product.feature'),
  ('super_admin', 'catalog.product.feature'),
  ('moderator', 'catalog.category.view'),
  ('editor', 'catalog.category.view'),
  ('admin', 'catalog.category.view'),
  ('super_admin', 'catalog.category.view'),
  ('admin', 'catalog.category.manage'),
  ('super_admin', 'catalog.category.manage'),
  ('supplier', 'catalog.inventory.manage'),
  ('admin', 'catalog.inventory.adjust_any'),
  ('super_admin', 'catalog.inventory.adjust_any'),
  ('supplier', 'catalog.batch.manage'),
  ('admin', 'catalog.batch.govern'),
  ('super_admin', 'catalog.batch.govern'),
  ('super_admin', 'catalog.batch.recall'),
  ('supplier', 'catalog.warehouse.manage'),
  ('admin', 'catalog.warehouse.govern'),
  ('super_admin', 'catalog.warehouse.govern'),
  ('moderator', 'moderation.dashboard.view'),
  ('admin', 'moderation.dashboard.view'),
  ('super_admin', 'moderation.dashboard.view'),
  ('moderator', 'moderation.product.view'),
  ('admin', 'moderation.product.view'),
  ('super_admin', 'moderation.product.view'),
  ('moderator', 'moderation.product.approve'),
  ('admin', 'moderation.product.approve'),
  ('super_admin', 'moderation.product.approve'),
  ('moderator', 'moderation.product.reject'),
  ('admin', 'moderation.product.reject'),
  ('super_admin', 'moderation.product.reject'),
  ('super_admin', 'moderation.product.auto_approve_config'),
  ('moderator', 'moderation.review.handle'),
  ('admin', 'moderation.review.handle'),
  ('super_admin', 'moderation.review.handle'),
  ('moderator', 'moderation.review.delete'),
  ('admin', 'moderation.review.delete'),
  ('super_admin', 'moderation.review.delete'),
  ('moderator', 'moderation.ugc.approve'),
  ('admin', 'moderation.ugc.approve'),
  ('super_admin', 'moderation.ugc.approve'),
  ('moderator', 'moderation.live.handle'),
  ('admin', 'moderation.live.handle'),
  ('super_admin', 'moderation.live.handle'),
  ('moderator', 'moderation.report.view'),
  ('admin', 'moderation.report.view'),
  ('super_admin', 'moderation.report.view'),
  ('moderator', 'moderation.report.handle'),
  ('admin', 'moderation.report.handle'),
  ('super_admin', 'moderation.report.handle'),
  ('moderator', 'moderation.queue.assign'),
  ('admin', 'moderation.queue.assign'),
  ('super_admin', 'moderation.queue.assign'),
  ('customer', 'orders.order.view_own'),
  ('saler', 'orders.order.view_own'),
  ('supplier', 'orders.order.view_own'),
  ('moderator', 'orders.order.view_all'),
  ('admin', 'orders.order.view_all'),
  ('super_admin', 'orders.order.view_all'),
  ('admin', 'orders.order.cancel'),
  ('super_admin', 'orders.order.cancel'),
  ('admin', 'orders.order.edit'),
  ('super_admin', 'orders.order.edit'),
  ('customer', 'orders.return.request'),
  ('moderator', 'orders.return.view_all'),
  ('admin', 'orders.return.view_all'),
  ('super_admin', 'orders.return.view_all'),
  ('moderator', 'orders.return.review'),
  ('admin', 'orders.return.review'),
  ('super_admin', 'orders.return.review'),
  ('moderator', 'orders.return.approve'),
  ('admin', 'orders.return.approve'),
  ('super_admin', 'orders.return.approve'),
  ('admin', 'orders.refund.execute'),
  ('super_admin', 'orders.refund.execute'),
  ('super_admin', 'orders.refund.execute_large'),
  ('moderator', 'orders.dispute.view_all'),
  ('admin', 'orders.dispute.view_all'),
  ('super_admin', 'orders.dispute.view_all'),
  ('moderator', 'orders.dispute.arbitrate'),
  ('admin', 'orders.dispute.arbitrate'),
  ('super_admin', 'orders.dispute.arbitrate'),
  ('moderator', 'orders.dispute.escalate'),
  ('admin', 'orders.dispute.escalate'),
  ('super_admin', 'orders.dispute.escalate'),
  ('admin', 'orders.cod.view'),
  ('super_admin', 'orders.cod.view'),
  ('admin', 'orders.cod.reconcile'),
  ('super_admin', 'orders.cod.reconcile'),
  ('admin', 'orders.cod.resolve_discrepancy'),
  ('super_admin', 'orders.cod.resolve_discrepancy'),
  ('supplier', 'logistics.shipment.view'),
  ('admin', 'logistics.shipment.view'),
  ('super_admin', 'logistics.shipment.view'),
  ('supplier', 'logistics.consignment.create'),
  ('supplier', 'logistics.consignment.cancel'),
  ('admin', 'logistics.consignment.cancel'),
  ('super_admin', 'logistics.consignment.cancel'),
  ('admin', 'logistics.carrier.view'),
  ('super_admin', 'logistics.carrier.view'),
  ('admin', 'logistics.carrier.manage'),
  ('super_admin', 'logistics.carrier.manage'),
  ('super_admin', 'logistics.carrier.credentials'),
  ('admin', 'logistics.routing.configure'),
  ('super_admin', 'logistics.routing.configure'),
  ('customer', 'finance.wallet.view_own'),
  ('saler', 'finance.wallet.view_own'),
  ('supplier', 'finance.wallet.view_own'),
  ('admin', 'finance.wallet.view_any'),
  ('super_admin', 'finance.wallet.view_any'),
  ('super_admin', 'finance.wallet.adjust'),
  ('admin', 'finance.overview.view'),
  ('super_admin', 'finance.overview.view'),
  ('admin', 'finance.ledger.view'),
  ('super_admin', 'finance.ledger.view'),
  ('admin', 'finance.ledger.export'),
  ('super_admin', 'finance.ledger.export'),
  ('admin', 'finance.integrity.check'),
  ('super_admin', 'finance.integrity.check'),
  ('admin', 'finance.escrow.view'),
  ('super_admin', 'finance.escrow.view'),
  ('admin', 'finance.escrow.freeze'),
  ('super_admin', 'finance.escrow.freeze'),
  ('super_admin', 'finance.escrow.release_manual'),
  ('saler', 'finance.payout.request'),
  ('supplier', 'finance.payout.request'),
  ('admin', 'finance.payout.view'),
  ('super_admin', 'finance.payout.view'),
  ('admin', 'finance.payout.reject'),
  ('super_admin', 'finance.payout.reject'),
  ('admin', 'finance.payout.approve'),
  ('super_admin', 'finance.payout.approve'),
  ('super_admin', 'finance.payout.approve_large'),
  ('admin', 'finance.payout.batch'),
  ('super_admin', 'finance.payout.batch'),
  ('admin', 'finance.split.view'),
  ('super_admin', 'finance.split.view'),
  ('super_admin', 'finance.split.update'),
  ('super_admin', 'finance.subscription.manage'),
  ('admin', 'finance.clawback.execute'),
  ('super_admin', 'finance.clawback.execute'),
  ('supplier', 'finance.b2b_escrow.view_own'),
  ('admin', 'finance.b2b_escrow.manage'),
  ('super_admin', 'finance.b2b_escrow.manage'),
  ('super_admin', 'finance.b2b_escrow.release'),
  ('saler', 'growth.ad.manage_own'),
  ('supplier', 'growth.ad.manage_own'),
  ('moderator', 'growth.ad.review'),
  ('admin', 'growth.ad.review'),
  ('super_admin', 'growth.ad.review'),
  ('admin', 'growth.ad.govern'),
  ('super_admin', 'growth.ad.govern'),
  ('saler', 'growth.coupon.create_own'),
  ('supplier', 'growth.coupon.create_own'),
  ('admin', 'growth.coupon.manage'),
  ('super_admin', 'growth.coupon.manage'),
  ('admin', 'growth.coupon.platform_wide'),
  ('super_admin', 'growth.coupon.platform_wide'),
  ('admin', 'growth.campaign.manage'),
  ('super_admin', 'growth.campaign.manage'),
  ('admin', 'growth.campaign.emergency_stop'),
  ('super_admin', 'growth.campaign.emergency_stop'),
  ('customer', 'growth.referral.view_own'),
  ('saler', 'growth.referral.view_own'),
  ('supplier', 'growth.referral.view_own'),
  ('super_admin', 'growth.referral.govern'),
  ('customer', 'growth.coins.view_own'),
  ('saler', 'growth.coins.view_own'),
  ('supplier', 'growth.coins.view_own'),
  ('admin', 'growth.coins.adjust'),
  ('super_admin', 'growth.coins.adjust'),
  ('super_admin', 'growth.coins.govern'),
  ('admin', 'growth.quest.govern'),
  ('super_admin', 'growth.quest.govern'),
  ('admin', 'growth.leaderboard.govern'),
  ('super_admin', 'growth.leaderboard.govern'),
  ('admin', 'growth.groupbuy.govern'),
  ('super_admin', 'growth.groupbuy.govern'),
  ('editor', 'content.dashboard.view'),
  ('admin', 'content.dashboard.view'),
  ('super_admin', 'content.dashboard.view'),
  ('editor', 'content.banner.publish'),
  ('admin', 'content.banner.publish'),
  ('super_admin', 'content.banner.publish'),
  ('editor', 'content.story.curate'),
  ('admin', 'content.story.curate'),
  ('super_admin', 'content.story.curate'),
  ('saler', 'content.story.publish_own'),
  ('supplier', 'content.story.publish_own'),
  ('editor', 'content.academy.manage'),
  ('admin', 'content.academy.manage'),
  ('super_admin', 'content.academy.manage'),
  ('editor', 'content.announcement.publish'),
  ('admin', 'content.announcement.publish'),
  ('super_admin', 'content.announcement.publish'),
  ('editor', 'content.i18n.update'),
  ('admin', 'content.i18n.update'),
  ('super_admin', 'content.i18n.update'),
  ('admin', 'content.i18n.locale_add'),
  ('super_admin', 'content.i18n.locale_add'),
  ('editor', 'content.help.manage'),
  ('admin', 'content.help.manage'),
  ('super_admin', 'content.help.manage'),
  ('customer', 'chat.thread.view_own'),
  ('saler', 'chat.thread.view_own'),
  ('supplier', 'chat.thread.view_own'),
  ('customer', 'chat.message.send'),
  ('saler', 'chat.message.send'),
  ('supplier', 'chat.message.send'),
  ('admin', 'chat.thread.view_any'),
  ('super_admin', 'chat.thread.view_any'),
  ('moderator', 'chat.message.moderate'),
  ('admin', 'chat.message.moderate'),
  ('super_admin', 'chat.message.moderate'),
  ('admin', 'chat.broadcast.send'),
  ('super_admin', 'chat.broadcast.send'),
  ('customer', 'live.stream.view'),
  ('saler', 'live.stream.view'),
  ('supplier', 'live.stream.view'),
  ('saler', 'live.stream.host'),
  ('supplier', 'live.stream.host'),
  ('moderator', 'live.stream.terminate'),
  ('admin', 'live.stream.terminate'),
  ('super_admin', 'live.stream.terminate'),
  ('admin', 'live.stream.govern'),
  ('super_admin', 'live.stream.govern'),
  ('customer', 'support.warranty.view_own'),
  ('supplier', 'support.warranty.view_own'),
  ('customer', 'support.warranty.claim'),
  ('supplier', 'support.warranty.manage'),
  ('admin', 'support.warranty.override'),
  ('super_admin', 'support.warranty.override'),
  ('saler', 'saler.dashboard.view'),
  ('saler', 'saler.store.manage'),
  ('saler', 'saler.sourcing.view'),
  ('saler', 'saler.order.view'),
  ('saler', 'saler.analytics.view'),
  ('saler', 'saler.bundle.manage'),
  ('supplier', 'supplier.dashboard.view'),
  ('supplier', 'supplier.order.view'),
  ('supplier', 'supplier.analytics.view'),
  ('supplier', 'supplier.store.manage'),
  ('customer', 'ai.concierge.use'),
  ('saler', 'ai.concierge.use'),
  ('supplier', 'ai.concierge.use'),
  ('saler', 'ai.sourcing.use'),
  ('saler', 'ai.creative.use'),
  ('supplier', 'ai.creative.use'),
  ('super_admin', 'ai.config.manage')
) AS x(role_key, permission_key)
JOIN roles r ON r.key = x.role_key
ON CONFLICT DO NOTHING;
