-- 003_modules.sql (Prompt 3.1)
-- Seeds platform_modules from server/src/config/modules.seed.json (Prompt 0.7),
-- default platform_settings, and default commission_rules.

INSERT INTO platform_modules (key, group_key, label_en, label_bn, description_en, description_bn, is_enabled, default_enabled, settings_json, settings_schema, depends_on)
VALUES
  ('supplier_verification', 'trust', 'Supplier verification', 'সরবরাহকারী যাচাই',
   'Suppliers must pass NID, trade licence and facility checks before listing products.',
   'পণ্য তালিকাভুক্ত করার আগে সরবরাহকারীদের এনআইডি, ট্রেড লাইসেন্স ও কারখানা যাচাই করতে হবে।',
   true, true, '{"require_trade_license": true, "require_facility_photos": true, "require_bank_match": true, "appeal_window_days": 30}'::jsonb,
   '{"type": "object", "properties": { "require_trade_license": { "type": "boolean", "default": true }, "require_facility_photos": { "type": "boolean", "default": true }, "require_bank_match": { "type": "boolean", "default": true }, "appeal_window_days": { "type": "integer", "minimum": 1, "maximum": 90, "default": 30 } } }'::jsonb,
   ARRAY[]::text[]),

  ('saler_verification', 'trust', 'Saler verification', 'সেলার যাচাই',
   'Lightweight NID plus OTP-verified phone for resellers.',
   'রিসেলারদের জন্য হালকা এনআইডি ও ওটিপি-যাচাইকৃত ফোন।',
   true, true, '{"require_nid": true, "allow_unverified_selling": true, "unverified_monthly_cap": 20000}'::jsonb,
   '{"type": "object", "properties": { "require_nid": { "type": "boolean", "default": true }, "allow_unverified_selling": { "type": "boolean", "default": true }, "unverified_monthly_cap": { "type": "number", "default": 20000 } } }'::jsonb,
   ARRAY[]::text[]),

  ('customer_verification', 'trust', 'Customer verification', 'ক্রেতা যাচাই',
   'Identity checks for shoppers. OFF by default to keep signup frictionless.',
   'ক্রেতাদের পরিচয় যাচাই। সাইনআপ সহজ রাখতে ডিফল্টে বন্ধ।',
   false, false, '{"mode": "DISABLED", "soft_threshold_amount": 5000}'::jsonb,
   '{"type": "object", "properties": { "mode": { "type": "string", "enum": ["DISABLED", "SOFT", "FULL"], "default": "DISABLED" }, "soft_threshold_amount": { "type": "number", "default": 5000 } } }'::jsonb,
   ARRAY[]::text[]),

  ('age_verification', 'trust', 'Age verification', 'বয়স যাচাই',
   'Date-of-birth and NID check for age-restricted categories.',
   'বয়স-সীমাবদ্ধ ক্যাটেগরির জন্য জন্মতারিখ ও এনআইডি যাচাই।',
   false, false, '{"minimum_age": 18, "restricted_category_ids": []}'::jsonb,
   '{"type": "object", "properties": { "minimum_age": { "type": "integer", "default": 18 }, "restricted_category_ids": { "type": "array", "items": { "type": "integer" } } } }'::jsonb,
   ARRAY['customer_verification']::text[]),

  ('product_moderation', 'trust', 'Product moderation queue', 'পণ্য মডারেশন সারি',
   'New and edited listings need human review before going live.',
   'নতুন ও সম্পাদিত পণ্য প্রকাশের আগে মানুষের পর্যালোচনা প্রয়োজন।',
   true, true, '{"sla_hours": 24, "keyword_blocklist_en": [], "keyword_blocklist_bn": [], "price_anomaly_multiplier": 5}'::jsonb,
   '{"type": "object", "properties": { "sla_hours": { "type": "integer", "minimum": 1, "maximum": 168, "default": 24 }, "keyword_blocklist_en": { "type": "array", "items": { "type": "string" } }, "keyword_blocklist_bn": { "type": "array", "items": { "type": "string" } }, "price_anomaly_multiplier": { "type": "number", "default": 5 } } }'::jsonb,
   ARRAY[]::text[]),

  ('auto_approval', 'trust', 'Auto-approve products', 'পণ্য স্বয়ংক্রিয় অনুমোদন',
   'Skip human review for chosen categories or trusted sellers.',
   'নির্বাচিত ক্যাটেগরি বা বিশ্বস্ত বিক্রেতার জন্য মানুষের পর্যালোচনা এড়ানো।',
   false, false, '{"category_ids": [], "min_seller_tier": "ELITE_PARTNER"}'::jsonb,
   '{"type": "object", "properties": { "category_ids": { "type": "array", "items": { "type": "integer" } }, "min_seller_tier": { "type": "string", "enum": ["STARTER", "VERIFIED_TRADER", "ELITE_PARTNER"], "default": "ELITE_PARTNER" } } }'::jsonb,
   ARRAY['product_moderation']::text[]),

  ('blue_tick_badge', 'trust', 'Blue-tick badge', 'ব্লু-টিক ব্যাজ',
   'Public verification badge on profiles and product cards.',
   'প্রোফাইল ও পণ্য কার্ডে প্রকাশ্য যাচাই ব্যাজ।',
   true, true, '{}'::jsonb, NULL,
   ARRAY['supplier_verification']::text[]),

  ('trust_tiers', 'trust', 'Seller trust tiers', 'বিক্রেতা ট্রাস্ট টিয়ার',
   'Starter to Elite Partner ladder affecting ranking, limits and ad eligibility.',
   'স্টার্টার থেকে এলিট পার্টনার ধাপ — র‍্যাংকিং, সীমা ও বিজ্ঞাপনের যোগ্যতা নির্ধারণ করে।',
   true, true, '{"verified_min_orders": 25, "elite_min_orders": 200, "elite_min_rating": 4.5, "elite_bonus_split_pct": 5}'::jsonb,
   '{"type": "object", "properties": { "verified_min_orders": { "type": "integer", "default": 25 }, "elite_min_orders": { "type": "integer", "default": 200 }, "elite_min_rating": { "type": "number", "default": 4.5 }, "elite_bonus_split_pct": { "type": "number", "default": 5 } } }'::jsonb,
   ARRAY[]::text[]),

  ('fraud_velocity_limits', 'trust', 'Fraud & velocity limits', 'জালিয়াতি ও গতিসীমা',
   'Automatic detection of abnormal account and transaction velocity.',
   'অস্বাভাবিক অ্যাকাউন্ট ও লেনদেনের গতি স্বয়ংক্রিয় শনাক্তকরণ।',
   true, true, '{"max_orders_per_hour": 10, "max_accounts_per_device": 3, "auto_restrict_on_breach": true}'::jsonb,
   '{"type": "object", "properties": { "max_orders_per_hour": { "type": "integer", "default": 10 }, "max_accounts_per_device": { "type": "integer", "default": 3 }, "auto_restrict_on_breach": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('review_integrity', 'trust', 'Review integrity checks', 'রিভিউ সততা যাচাই',
   'Scores reviews for authenticity and flags suspicious ones for moderation.',
   'রিভিউর সত্যতা যাচাই করে সন্দেহজনকগুলো মডারেশনে পাঠায়।',
   true, true, '{"flag_threshold": 60, "require_verified_purchase": true}'::jsonb,
   '{"type": "object", "properties": { "flag_threshold": { "type": "integer", "minimum": 0, "maximum": 100, "default": 60 }, "require_verified_purchase": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('duplicate_account_detection', 'trust', 'Duplicate account detection', 'ডুপ্লিকেট অ্যাকাউন্ট শনাক্তকরণ',
   'Cross-checks NID hash, phone and device fingerprint at signup.',
   'সাইনআপে এনআইডি হ্যাশ, ফোন ও ডিভাইস ফিঙ্গারপ্রিন্ট মিলিয়ে দেখে।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('user_reports', 'trust', 'User reports & flags', 'ইউজার রিপোর্ট ও ফ্ল্যাগ',
   'Lets the community report suspicious products, reviews and accounts.',
   'সন্দেহজনক পণ্য, রিভিউ ও অ্যাকাউন্ট সম্পর্কে কমিউনিটিকে রিপোর্ট করতে দেয়।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('onboarding_agreements', 'trust', 'Policy acceptance at signup', 'সাইনআপে নীতি গ্রহণ',
   'Users must accept terms and the seller agreement during onboarding.',
   'অনবোর্ডিংয়ের সময় ইউজারকে শর্তাবলি ও বিক্রেতা চুক্তি মানতে হবে।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('terms_reacceptance', 'trust', 'Re-accept updated terms', 'হালনাগাদ শর্ত পুনরায় গ্রহণ',
   'Prompts existing users to accept a new policy version.',
   'নতুন নীতির সংস্করণ গ্রহণ করতে বিদ্যমান ইউজারদের অনুরোধ করে।',
   true, true, '{"grace_period_days": 14, "block_after_grace": false}'::jsonb,
   '{"type": "object", "properties": { "grace_period_days": { "type": "integer", "default": 14 }, "block_after_grace": { "type": "boolean", "default": false } } }'::jsonb,
   ARRAY['onboarding_agreements']::text[]),

  ('cod_protection', 'trust', 'COD fraud protection', 'সিওডি জালিয়াতি সুরক্ষা',
   'OTP confirmation and trust scoring to reduce fake cash-on-delivery orders.',
   'ভুয়া ক্যাশ-অন-ডেলিভারি অর্ডার কমাতে ওটিপি নিশ্চিতকরণ ও ট্রাস্ট স্কোর।',
   true, true, '{"otp_threshold_amount": 2000, "max_cod_value": 25000, "min_trust_score": 30, "advance_charge_below_score": 20}'::jsonb,
   '{"type": "object", "properties": { "otp_threshold_amount": { "type": "number", "default": 2000 }, "max_cod_value": { "type": "number", "default": 25000 }, "min_trust_score": { "type": "integer", "default": 30 }, "advance_charge_below_score": { "type": "integer", "default": 20 } } }'::jsonb,
   ARRAY['cod_payment']::text[]),

  ('virtual_storefront', 'commerce', 'Virtual storefronts', 'ভার্চুয়াল স্টোরফ্রন্ট',
   'Branded reseller shops at explooro.com/store/name.',
   'explooro.com/store/নাম ঠিকানায় ব্র্যান্ডেড রিসেলার দোকান।',
   true, true, '{"allow_custom_domain": false, "min_tier_for_custom_domain": "ELITE_PARTNER"}'::jsonb,
   '{"type": "object", "properties": { "allow_custom_domain": { "type": "boolean", "default": false }, "min_tier_for_custom_domain": { "type": "string", "enum": ["VERIFIED_TRADER", "ELITE_PARTNER"], "default": "ELITE_PARTNER" } } }'::jsonb,
   ARRAY[]::text[]),

  ('sourcing', 'commerce', 'Supplier sourcing catalog', 'সরবরাহকারী সোর্সিং ক্যাটালগ',
   'Lets salers browse supplier stock and add items to their store in one click.',
   'সেলাররা সরবরাহকারীর স্টক দেখে এক ক্লিকে নিজের দোকানে যোগ করতে পারে।',
   true, true, '{"min_margin_pct": 10, "allow_price_override": true}'::jsonb,
   '{"type": "object", "properties": { "min_margin_pct": { "type": "number", "default": 10 }, "allow_price_override": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY['virtual_storefront']::text[]),

  ('wishlist', 'commerce', 'Wishlist & price alerts', 'উইশলিস্ট ও দাম কমার সতর্কতা',
   'Saved items with optional price-drop notifications.',
   'সংরক্ষিত পণ্য, সাথে দাম কমার নোটিফিকেশন।',
   true, true, '{"price_drop_threshold_pct": 5}'::jsonb,
   '{"type": "object", "properties": { "price_drop_threshold_pct": { "type": "number", "default": 5 } } }'::jsonb,
   ARRAY[]::text[]),

  ('quick_buy', 'commerce', '1-click quick buy', '১-ক্লিক দ্রুত কেনা',
   'Two-step checkout overlay that bypasses the cart.',
   'কার্ট এড়িয়ে দুই ধাপের দ্রুত চেকআউট।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('voice_search', 'commerce', 'Voice search', 'ভয়েস সার্চ',
   'Spoken product search in Bengali and English.',
   'বাংলা ও ইংরেজিতে কথা বলে পণ্য খোঁজা।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('physical_shop_status', 'commerce', 'Physical shop open/closed', 'দোকান খোলা/বন্ধ',
   'Live open or closed indicator with business hours for brick-and-mortar sellers.',
   'দোকানদারদের জন্য ব্যবসার সময়সহ খোলা/বন্ধ নির্দেশক।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('product_bundling', 'commerce', 'Cross-seller bundles', 'ক্রস-সেলার বান্ডেল',
   'Combine items from multiple suppliers into a discounted pack with automatic profit splitting.',
   'একাধিক সরবরাহকারীর পণ্য মিলিয়ে ছাড়ের প্যাক, স্বয়ংক্রিয় মুনাফা বণ্টনসহ।',
   true, true, '{"max_items_per_bundle": 5, "max_discount_pct": 25}'::jsonb,
   '{"type": "object", "properties": { "max_items_per_bundle": { "type": "integer", "default": 5 }, "max_discount_pct": { "type": "number", "default": 25 } } }'::jsonb,
   ARRAY['sourcing']::text[]),

  ('fefo_batches', 'commerce', 'Batch & expiry (FEFO)', 'ব্যাচ ও মেয়াদ (ফিফো)',
   'Lot tracking with first-expire-first-out dispatch and recall support.',
   'লট ট্র্যাকিং, আগে মেয়াদ শেষ হওয়া আগে পাঠানো ও রিকল সুবিধা।',
   true, true, '{"warn_days_before_expiry": [60, 30], "block_dispatch_within_days": 7, "mandatory_categories": []}'::jsonb,
   '{"type": "object", "properties": { "warn_days_before_expiry": { "type": "array", "items": { "type": "integer" }, "default": [60, 30] }, "block_dispatch_within_days": { "type": "integer", "default": 7 }, "mandatory_categories": { "type": "array", "items": { "type": "integer" } } } }'::jsonb,
   ARRAY[]::text[]),

  ('multi_warehouse', 'commerce', 'Multi-warehouse routing', 'একাধিক গুদাম রাউটিং',
   'Routes each order to the nearest depot holding stock.',
   'প্রতিটি অর্ডার স্টক আছে এমন নিকটতম গুদামে পাঠায়।',
   true, true, '{"max_distance_km": 400, "allow_split_across_warehouses": true}'::jsonb,
   '{"type": "object", "properties": { "max_distance_km": { "type": "number", "default": 400 }, "allow_split_across_warehouses": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('demand_surge', 'commerce', 'Demand surge suggestions', 'চাহিদা বৃদ্ধির পরামর্শ',
   'Recommends price adjustments on high-demand items. Never applies them automatically.',
   'বেশি চাহিদার পণ্যে দাম সমন্বয়ের পরামর্শ দেয়। কখনো নিজে থেকে প্রয়োগ করে না।',
   true, true, '{"max_increase_pct": 15, "require_seller_optin": true}'::jsonb,
   '{"type": "object", "properties": { "max_increase_pct": { "type": "number", "default": 15 }, "require_seller_optin": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('group_buying', 'commerce', 'Team purchase (group buying)', 'টিম পারচেজ (গ্রুপ কেনাকাটা)',
   'Buyers form a team within a countdown window to unlock a lower price.',
   'নির্দিষ্ট সময়ের মধ্যে ক্রেতারা দল গড়ে কম দাম পায়।',
   true, true, '{"default_team_size": 3, "window_hours": 24, "min_discount_pct": 10}'::jsonb,
   '{"type": "object", "properties": { "default_team_size": { "type": "integer", "minimum": 2, "default": 3 }, "window_hours": { "type": "integer", "default": 24 }, "min_discount_pct": { "type": "number", "default": 10 } } }'::jsonb,
   ARRAY[]::text[]),

  ('cart_recovery', 'commerce', 'Abandoned cart recovery', 'পরিত্যক্ত কার্ট পুনরুদ্ধার',
   'Automated reminders and optional incentives for carts left unfinished.',
   'অসম্পূর্ণ কার্টের জন্য স্বয়ংক্রিয় মনে করিয়ে দেওয়া ও ঐচ্ছিক ছাড়।',
   true, true, '{"detect_after_minutes": 60, "sequence_hours": [1, 24, 72], "max_incentive_pct": 10, "cooldown_days": 14}'::jsonb,
   '{"type": "object", "properties": { "detect_after_minutes": { "type": "integer", "default": 60 }, "sequence_hours": { "type": "array", "items": { "type": "integer" }, "default": [1, 24, 72] }, "max_incentive_pct": { "type": "number", "default": 10 }, "cooldown_days": { "type": "integer", "default": 14 } } }'::jsonb,
   ARRAY[]::text[]),

  ('cod_payment', 'finance', 'Cash on delivery', 'ক্যাশ অন ডেলিভারি',
   'Pay the courier in cash at the door.',
   'দরজায় কুরিয়ারকে নগদ পরিশোধ।',
   true, true, '{"enabled_districts": [], "advance_charge_amount": 0}'::jsonb,
   '{"type": "object", "properties": { "enabled_districts": { "type": "array", "items": { "type": "string" } }, "advance_charge_amount": { "type": "number", "default": 0 } } }'::jsonb,
   ARRAY[]::text[]),

  ('mfs_payment', 'finance', 'bKash / Nagad / Rocket', 'বিকাশ / নগদ / রকেট',
   'Mobile financial services checkout.',
   'মোবাইল ব্যাংকিংয়ে পেমেন্ট।',
   true, true, '{"bkash_enabled": true, "nagad_enabled": true, "rocket_enabled": false}'::jsonb,
   '{"type": "object", "properties": { "bkash_enabled": { "type": "boolean", "default": true }, "nagad_enabled": { "type": "boolean", "default": true }, "rocket_enabled": { "type": "boolean", "default": false } } }'::jsonb,
   ARRAY[]::text[]),

  ('card_payment', 'finance', 'Debit / credit card', 'ডেবিট / ক্রেডিট কার্ড',
   'Card checkout through SSLCommerz. Off until the gateway is live.',
   'এসএসএলকমার্সের মাধ্যমে কার্ড পেমেন্ট। গেটওয়ে চালু না হওয়া পর্যন্ত বন্ধ।',
   false, false, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('subscription_fees', 'finance', 'Seller subscription & fees', 'বিক্রেতা সাবস্ক্রিপশন ও ফি',
   'Optional listing or membership fees. Platform is free at launch.',
   'ঐচ্ছিক লিস্টিং বা সদস্য ফি। চালুর সময় প্ল্যাটফর্ম সম্পূর্ণ ফ্রি।',
   false, false, '{"monthly_fee": 0, "listing_fee": 0, "free_listing_quota": 100}'::jsonb,
   '{"type": "object", "properties": { "monthly_fee": { "type": "number", "default": 0 }, "listing_fee": { "type": "number", "default": 0 }, "free_listing_quota": { "type": "integer", "default": 100 } } }'::jsonb,
   ARRAY[]::text[]),

  ('escrow_engine', 'finance', 'Escrow holding period', 'এসক্রো ধরে রাখার সময়',
   'Holds seller commission until the return window closes.',
   'রিটার্নের সময় শেষ না হওয়া পর্যন্ত বিক্রেতার কমিশন আটকে রাখে।',
   true, true, '{"hold_days": 7, "elite_hold_days": 3}'::jsonb,
   '{"type": "object", "properties": { "hold_days": { "type": "integer", "minimum": 0, "maximum": 60, "default": 7 }, "elite_hold_days": { "type": "integer", "default": 3 } } }'::jsonb,
   ARRAY[]::text[]),

  ('b2b_escrow', 'finance', 'B2B milestone escrow', 'বি২বি ধাপভিত্তিক এসক্রো',
   'Large wholesale deals released in stages against evidence.',
   'বড় পাইকারি চুক্তি প্রমাণের ভিত্তিতে ধাপে ধাপে ছাড়া হয়।',
   true, true, '{"min_order_value": 100000, "default_milestones_pct": [30, 40, 30]}'::jsonb,
   '{"type": "object", "properties": { "min_order_value": { "type": "number", "default": 100000 }, "default_milestones_pct": { "type": "array", "items": { "type": "number" }, "default": [30, 40, 30] } } }'::jsonb,
   ARRAY['escrow_engine']::text[]),

  ('cod_reconciliation', 'finance', 'COD reconciliation', 'সিওডি হিসাব মিলানো',
   'Three-way match of expected cash, courier report and bank deposit before escrow releases.',
   'এসক্রো ছাড়ার আগে প্রত্যাশিত নগদ, কুরিয়ার রিপোর্ট ও ব্যাংক জমা মিলিয়ে দেখা।',
   true, true, '{"auto_match_tolerance": 1, "alert_after_days": 7}'::jsonb,
   '{"type": "object", "properties": { "auto_match_tolerance": { "type": "number", "default": 1 }, "alert_after_days": { "type": "integer", "default": 7 } } }'::jsonb,
   ARRAY['cod_payment', 'escrow_engine']::text[]),

  ('courier_hub', 'logistics', 'Courier hub & tracking', 'কুরিয়ার হাব ও ট্র্যাকিং',
   'Steadfast, Pathao, RedX and Paperfly integration with live status webhooks.',
   'স্টেডফাস্ট, পাঠাও, রেডএক্স ও পেপারফ্লাই সংযোগ, লাইভ স্ট্যাটাস ওয়েবহুকসহ।',
   true, true, '{"preferred_order": ["STEADFAST", "PATHAO", "REDX", "PAPERFLY"], "enable_live_map": true}'::jsonb,
   '{"type": "object", "properties": { "preferred_order": { "type": "array", "items": { "type": "string" }, "default": ["STEADFAST", "PATHAO", "REDX", "PAPERFLY"] }, "enable_live_map": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('returns_engine', 'logistics', 'Returns & refunds', 'রিটার্ন ও রিফান্ড',
   'Customer-initiated returns with evidence, inspection and refund.',
   'ক্রেতার শুরু করা রিটার্ন — প্রমাণ, পরীক্ষা ও রিফান্ডসহ।',
   true, true, '{"return_window_days": 7, "allowed_reasons": ["DAMAGED", "WRONG_ITEM", "NOT_AS_DESCRIBED", "MISSING_PARTS", "SIZE_ISSUE"], "require_evidence_for": ["DAMAGED", "WRONG_ITEM"], "auto_approve_below_amount": 0, "abuse_return_rate_pct": 40}'::jsonb,
   '{"type": "object", "properties": { "return_window_days": { "type": "integer", "minimum": 0, "maximum": 60, "default": 7 }, "allowed_reasons": { "type": "array", "items": { "type": "string" }, "default": ["DAMAGED", "WRONG_ITEM", "NOT_AS_DESCRIBED", "MISSING_PARTS", "SIZE_ISSUE"] }, "require_evidence_for": { "type": "array", "items": { "type": "string" }, "default": ["DAMAGED", "WRONG_ITEM"] }, "auto_approve_below_amount": { "type": "number", "default": 0 }, "abuse_return_rate_pct": { "type": "number", "default": 40 } } }'::jsonb,
   ARRAY[]::text[]),

  ('dispute_panel', 'logistics', 'Dispute arbitration', 'বিরোধ নিষ্পত্তি',
   'Three-way mediation between buyer, saler and supplier.',
   'ক্রেতা, সেলার ও সরবরাহকারীর মধ্যে ত্রিপক্ষীয় মধ্যস্থতা।',
   true, true, '{"sla_hours": 48, "escalate_above_amount": 10000, "maker_checker_above_amount": 5000}'::jsonb,
   '{"type": "object", "properties": { "sla_hours": { "type": "integer", "default": 48 }, "escalate_above_amount": { "type": "number", "default": 10000 }, "maker_checker_above_amount": { "type": "number", "default": 5000 } } }'::jsonb,
   ARRAY['returns_engine']::text[]),

  ('digital_warranty', 'logistics', 'Digital warranty & claims', 'ডিজিটাল ওয়ারেন্টি ও দাবি',
   'Warranty cards issued on delivery, with repair and replacement claims.',
   'ডেলিভারিতে ওয়ারেন্টি কার্ড, সাথে মেরামত ও প্রতিস্থাপনের দাবি।',
   true, true, '{"claim_sla_hours": 72, "allow_transfer_on_resale": false}'::jsonb,
   '{"type": "object", "properties": { "claim_sla_hours": { "type": "integer", "default": 72 }, "allow_transfer_on_resale": { "type": "boolean", "default": false } } }'::jsonb,
   ARRAY[]::text[]),

  ('chat', 'communication', 'Real-time chat', 'রিয়েল-টাইম চ্যাট',
   'Live messaging between customer, saler and supplier.',
   'ক্রেতা, সেলার ও সরবরাহকারীর মধ্যে সরাসরি বার্তা।',
   true, true, '{"max_messages_per_minute": 60, "detect_contact_sharing": true, "offline_fallback_channel": "PUSH"}'::jsonb,
   '{"type": "object", "properties": { "max_messages_per_minute": { "type": "integer", "default": 60 }, "detect_contact_sharing": { "type": "boolean", "default": true }, "offline_fallback_channel": { "type": "string", "enum": ["PUSH", "SMS", "NONE"], "default": "PUSH" } } }'::jsonb,
   ARRAY[]::text[]),

  ('sms_notifications', 'communication', 'SMS notifications', 'এসএমএস নোটিফিকেশন',
   'Order milestones and OTP over the local SMS gateway.',
   'স্থানীয় এসএমএস গেটওয়ে দিয়ে অর্ডারের ধাপ ও ওটিপি।',
   true, true, '{"send_on_placed": true, "send_on_shipped": true, "send_on_delivered": true, "daily_cap_per_user": 10}'::jsonb,
   '{"type": "object", "properties": { "send_on_placed": { "type": "boolean", "default": true }, "send_on_shipped": { "type": "boolean", "default": true }, "send_on_delivered": { "type": "boolean", "default": true }, "daily_cap_per_user": { "type": "integer", "default": 10 } } }'::jsonb,
   ARRAY[]::text[]),

  ('push_notifications', 'communication', 'Push notifications', 'পুশ নোটিফিকেশন',
   'In-app and mobile push alerts.',
   'অ্যাপ ও মোবাইলে পুশ সতর্কতা।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('email_notifications', 'communication', 'Email notifications', 'ইমেইল নোটিফিকেশন',
   'Receipts, approvals and account notices by email.',
   'রসিদ, অনুমোদন ও অ্যাকাউন্ট বিজ্ঞপ্তি ইমেইলে।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('whatsapp_bridge', 'communication', 'WhatsApp & Messenger commerce', 'হোয়াটসঅ্যাপ ও মেসেঞ্জার কমার্স',
   'Syncs Meta chats into one inbox with in-chat product cards and checkout links.',
   'মেটার চ্যাট এক ইনবক্সে আনে, চ্যাটেই পণ্য কার্ড ও চেকআউট লিংকসহ।',
   true, true, '{"checkout_link_ttl_minutes": 60}'::jsonb,
   '{"type": "object", "properties": { "checkout_link_ttl_minutes": { "type": "integer", "default": 60 } } }'::jsonb,
   ARRAY['chat']::text[]),

  ('whats_new', 'communication', 'What''s New announcements', 'নতুন কী — ঘোষণা',
   'One-time release-note popup after each platform update.',
   'প্রতিটি হালনাগাদের পর একবার দেখানো রিলিজ নোট পপআপ।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('sponsored_ads', 'growth', 'Sponsored ads engine', 'স্পন্সর্ড বিজ্ঞাপন ইঞ্জিন',
   'Sellers pay to boost listings in search, category banners and the feed.',
   'বিক্রেতারা টাকা দিয়ে সার্চ, ক্যাটেগরি ব্যানার ও ফিডে পণ্য প্রচার করে।',
   true, true, '{"max_ads_per_page": 3, "min_daily_budget": 50, "require_creative_review": true, "blocked_keywords": []}'::jsonb,
   '{"type": "object", "properties": { "max_ads_per_page": { "type": "integer", "default": 3 }, "min_daily_budget": { "type": "number", "default": 50 }, "require_creative_review": { "type": "boolean", "default": true }, "blocked_keywords": { "type": "array", "items": { "type": "string" } } } }'::jsonb,
   ARRAY[]::text[]),

  ('coupons', 'growth', 'Coupons & vouchers', 'কুপন ও ভাউচার',
   'Discount codes scoped to the platform, a supplier, a saler, a category or a product.',
   'প্ল্যাটফর্ম, সরবরাহকারী, সেলার, ক্যাটেগরি বা পণ্যভিত্তিক ছাড়ের কোড।',
   true, true, '{"allow_stacking": false, "max_discount_pct": 50, "seller_coupons_need_review": false}'::jsonb,
   '{"type": "object", "properties": { "allow_stacking": { "type": "boolean", "default": false }, "max_discount_pct": { "type": "number", "default": 50 }, "seller_coupons_need_review": { "type": "boolean", "default": false } } }'::jsonb,
   ARRAY[]::text[]),

  ('flash_sale', 'growth', 'Flash sales', 'ফ্ল্যাশ সেল',
   'Time-boxed deals with reserved stock and a live countdown.',
   'নির্দিষ্ট সময়ের অফার, আলাদা রাখা স্টক ও লাইভ কাউন্টডাউনসহ।',
   true, true, '{"max_duration_hours": 24, "default_per_user_limit": 1}'::jsonb,
   '{"type": "object", "properties": { "max_duration_hours": { "type": "integer", "default": 24 }, "default_per_user_limit": { "type": "integer", "default": 1 } } }'::jsonb,
   ARRAY['coupons']::text[]),

  ('referral_engine', 'growth', 'Referral & network growth', 'রেফারেল ও নেটওয়ার্ক প্রবৃদ্ধি',
   'Multi-tier invite rewards with fraud controls and a holding period.',
   'বহুস্তরের আমন্ত্রণ পুরস্কার, জালিয়াতি নিয়ন্ত্রণ ও অপেক্ষার সময়সহ।',
   true, true, '{"tier_depth": 2, "tier_rates_pct": [5, 2], "qualifying_event": "FIRST_ORDER", "holding_days": 14}'::jsonb,
   '{"type": "object", "properties": { "tier_depth": { "type": "integer", "minimum": 1, "maximum": 3, "default": 2 }, "tier_rates_pct": { "type": "array", "items": { "type": "number" }, "default": [5, 2] }, "qualifying_event": { "type": "string", "enum": ["SIGNUP", "FIRST_ORDER", "FIRST_SALE", "KYC"], "default": "FIRST_ORDER" }, "holding_days": { "type": "integer", "default": 14 } } }'::jsonb,
   ARRAY[]::text[]),

  ('loyalty_coins', 'growth', 'Explooro Coins', 'এক্সপ্লোরো কয়েন',
   'Loyalty points earned on check-ins, orders and reviews, redeemable at checkout.',
   'চেক-ইন, অর্ডার ও রিভিউতে অর্জিত পয়েন্ট, চেকআউটে ব্যবহারযোগ্য।',
   true, true, '{"checkin_reward": 10, "streak_multiplier": 1.5, "review_reward": 20, "video_review_reward": 40, "redemption_rate": 0.1, "max_redeem_pct": 20, "expiry_days": 365}'::jsonb,
   '{"type": "object", "properties": { "checkin_reward": { "type": "integer", "default": 10 }, "streak_multiplier": { "type": "number", "default": 1.5 }, "review_reward": { "type": "integer", "default": 20 }, "video_review_reward": { "type": "integer", "default": 40 }, "redemption_rate": { "type": "number", "default": 0.1 }, "max_redeem_pct": { "type": "number", "default": 20 }, "expiry_days": { "type": "integer", "default": 365 } } }'::jsonb,
   ARRAY[]::text[]),

  ('gamification', 'growth', 'Leaderboard & seller rewards', 'লিডারবোর্ড ও বিক্রেতা পুরস্কার',
   'Monthly rankings with a bonus pool for top salers.',
   'মাসিক র‍্যাংকিং, শীর্ষ সেলারদের জন্য বোনাস পুল।',
   true, true, '{"monthly_bonus_pool": 50000, "top_n_rewarded": 20, "metrics": ["REVENUE", "ORDERS", "RATING"]}'::jsonb,
   '{"type": "object", "properties": { "monthly_bonus_pool": { "type": "number", "default": 50000 }, "top_n_rewarded": { "type": "integer", "default": 20 }, "metrics": { "type": "array", "items": { "type": "string" }, "default": ["REVENUE", "ORDERS", "RATING"] } } }'::jsonb,
   ARRAY[]::text[]),

  ('daily_quests', 'growth', 'Daily quests & missions', 'দৈনিক কোয়েস্ট ও মিশন',
   'Repeatable tasks that award coins and ad credits.',
   'পুনরাবৃত্তিযোগ্য কাজ যা কয়েন ও বিজ্ঞাপন ক্রেডিট দেয়।',
   true, true, '{"daily_quest_count": 3, "weekly_quest_count": 2}'::jsonb,
   '{"type": "object", "properties": { "daily_quest_count": { "type": "integer", "default": 3 }, "weekly_quest_count": { "type": "integer", "default": 2 } } }'::jsonb,
   ARRAY['loyalty_coins']::text[]),

  ('social_seller_kit', 'growth', 'Social seller kit', 'সোশ্যাল সেলার কিট',
   'Auto-generated flyers, QR codes and tracked affiliate short links.',
   'স্বয়ংক্রিয় ফ্লায়ার, কিউআর কোড ও ট্র্যাকযোগ্য অ্যাফিলিয়েট শর্ট লিংক।',
   true, true, '{}'::jsonb, NULL,
   ARRAY['virtual_storefront']::text[]),

  ('follow_feed', 'growth', 'Follow & follower feed', 'ফলো ও ফলোয়ার ফিড',
   'Shoppers follow sellers and see their product drops and live streams.',
   'ক্রেতারা বিক্রেতাদের ফলো করে তাদের নতুন পণ্য ও লাইভ দেখে।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('content_commerce', 'content', 'Storytelling posts', 'স্টোরিটেলিং পোস্ট',
   'Blog-style seller stories with buyable product cards embedded.',
   'ব্লগ-ধাঁচের বিক্রেতা গল্প, ভেতরে কেনার মতো পণ্য কার্ডসহ।',
   true, true, '{"require_moderation": true}'::jsonb,
   '{"type": "object", "properties": { "require_moderation": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('ugc_video_wall', 'content', 'UGC video reviews & reels', 'ইউজার ভিডিও রিভিউ ও রিলস',
   'Shoppable short-video feed of unboxing and review clips.',
   'আনবক্সিং ও রিভিউ ক্লিপের কেনাকাটা-যোগ্য শর্ট ভিডিও ফিড।',
   true, true, '{"max_duration_seconds": 15, "require_moderation": true, "data_saver_default": true}'::jsonb,
   '{"type": "object", "properties": { "max_duration_seconds": { "type": "integer", "default": 15 }, "require_moderation": { "type": "boolean", "default": true }, "data_saver_default": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('live_commerce', 'content', 'Live stream commerce', 'লাইভ স্ট্রিম কমার্স',
   'Live video selling with pinned products and in-stream checkout.',
   'লাইভ ভিডিওতে বিক্রি — পিন করা পণ্য ও সরাসরি চেকআউটসহ।',
   true, true, '{"max_concurrent_streams": 20, "max_duration_minutes": 120, "min_tier_to_host": "VERIFIED_TRADER", "enable_audio_only_fallback": true}'::jsonb,
   '{"type": "object", "properties": { "max_concurrent_streams": { "type": "integer", "default": 20 }, "max_duration_minutes": { "type": "integer", "default": 120 }, "min_tier_to_host": { "type": "string", "enum": ["STARTER", "VERIFIED_TRADER", "ELITE_PARTNER"], "default": "VERIFIED_TRADER" }, "enable_audio_only_fallback": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY['chat']::text[]),

  ('seller_academy', 'content', 'Seller Academy', 'সেলার একাডেমি',
   'Micro-learning video and audio courses on selling.',
   'বিক্রির উপর ছোট ভিডিও ও অডিও কোর্স।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('video_walkthroughs', 'content', '15-second walkthroughs', '১৫ সেকেন্ডের নির্দেশনা',
   'Short in-context tutorials for users with low reading confidence.',
   'কম পড়তে পারা ইউজারদের জন্য সংক্ষিপ্ত প্রাসঙ্গিক নির্দেশনা।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('i18n', 'content', 'Multi-language engine', 'বহু-ভাষা ইঞ্জিন',
   'English and Bengali interface with live translation management.',
   'ইংরেজি ও বাংলা ইন্টারফেস, সরাসরি অনুবাদ ব্যবস্থাপনাসহ।',
   true, true, '{"default_locale": "bn", "allow_bengali_numerals": true}'::jsonb,
   '{"type": "object", "properties": { "default_locale": { "type": "string", "enum": ["bn", "en"], "default": "bn" }, "allow_bengali_numerals": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('theme_studio', 'content', 'Theme & colour studio', 'থিম ও রঙ স্টুডিও',
   'Per-section colour control with marketplace presets and contrast validation.',
   'প্রতিটি অংশের আলাদা রঙ নিয়ন্ত্রণ, প্রিসেট ও কনট্রাস্ট যাচাইসহ।',
   true, true, '{"enforce_wcag_aa": true, "allow_gradients": false}'::jsonb,
   '{"type": "object", "properties": { "enforce_wcag_aa": { "type": "boolean", "default": true }, "allow_gradients": { "type": "boolean", "default": false } } }'::jsonb,
   ARRAY[]::text[]),

  ('seo_public_pages', 'content', 'SEO product pages', 'এসইও পণ্য পাতা',
   'Prerendered, crawlable product and store pages with structured data.',
   'স্ট্রাকচার্ড ডেটাসহ আগে থেকে রেন্ডার করা, ক্রল-যোগ্য পণ্য ও দোকান পাতা।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('og_share_cards', 'content', 'Social share cards', 'সোশ্যাল শেয়ার কার্ড',
   'Generated OpenGraph images so WhatsApp and Facebook shares look professional.',
   'তৈরি করা ওপেনগ্রাফ ছবি — হোয়াটসঅ্যাপ ও ফেসবুক শেয়ার সুন্দর দেখায়।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('xml_sitemap', 'content', 'Dynamic XML sitemap', 'ডাইনামিক এক্সএমএল সাইটম্যাপ',
   'Auto-generated sitemap index submitted to search engines.',
   'স্বয়ংক্রিয় সাইটম্যাপ যা সার্চ ইঞ্জিনে জমা দেওয়া হয়।',
   true, true, '{}'::jsonb, NULL,
   ARRAY['seo_public_pages']::text[]),

  ('ai_concierge', 'advanced', 'AI shopping assistant', 'এআই শপিং সহকারী',
   'Natural-language product discovery grounded in the real catalog.',
   'আসল ক্যাটালগের ভিত্তিতে স্বাভাবিক ভাষায় পণ্য খোঁজা।',
   true, true, '{"max_turns_per_session": 20, "daily_message_cap_per_user": 50}'::jsonb,
   '{"type": "object", "properties": { "max_turns_per_session": { "type": "integer", "default": 20 }, "daily_message_cap_per_user": { "type": "integer", "default": 50 } } }'::jsonb,
   ARRAY[]::text[]),

  ('ai_sourcing_chat', 'advanced', 'AI sourcing assistant', 'এআই সোর্সিং সহকারী',
   'Finds high-margin, trending supplier products for salers.',
   'সেলারদের জন্য বেশি লাভের ও জনপ্রিয় পণ্য খুঁজে দেয়।',
   true, true, '{}'::jsonb, NULL,
   ARRAY['sourcing']::text[]),

  ('ai_creative_studio', 'advanced', 'AI creative studio', 'এআই ক্রিয়েটিভ স্টুডিও',
   'Generates ad copy and cleans up product photo backgrounds. Output always needs human approval.',
   'বিজ্ঞাপনের লেখা তৈরি ও পণ্যের ছবির পটভূমি পরিষ্কার করে। ফলাফল সবসময় মানুষের অনুমোদন লাগে।',
   true, true, '{"monthly_generations_per_user": 100, "require_human_approval": true}'::jsonb,
   '{"type": "object", "properties": { "monthly_generations_per_user": { "type": "integer", "default": 100 }, "require_human_approval": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('ai_forecasting', 'advanced', 'Demand forecasting', 'চাহিদা পূর্বাভাস',
   'Statistical stockout and seasonal-peak prediction with AI explanations.',
   'পরিসংখ্যানভিত্তিক স্টক শেষ হওয়া ও মৌসুমি চাহিদার পূর্বাভাস, এআই ব্যাখ্যাসহ।',
   true, true, '{"horizon_days": 30, "min_history_days": 60}'::jsonb,
   '{"type": "object", "properties": { "horizon_days": { "type": "integer", "default": 30 }, "min_history_days": { "type": "integer", "default": 60 } } }'::jsonb,
   ARRAY[]::text[]),

  ('prescriptive_insights', 'advanced', 'Next-action insights', 'পরবর্তী পদক্ষেপের পরামর্শ',
   'Actionable recommendations based on each user''s own metrics.',
   'প্রতিটি ইউজারের নিজের পরিসংখ্যান দেখে কাজে লাগানোর মতো পরামর্শ।',
   true, true, '{}'::jsonb, NULL,
   ARRAY[]::text[]),

  ('open_api', 'system', 'Open API & webhooks', 'ওপেন এপিআই ও ওয়েবহুক',
   'Scoped developer API keys, outbound webhooks and an embeddable product widget.',
   'সীমিত অনুমতির ডেভেলপার এপিআই কী, আউটবাউন্ড ওয়েবহুক ও এমবেডযোগ্য পণ্য উইজেট।',
   true, true, '{"default_rate_limit_per_min": 60, "allow_write_api": false}'::jsonb,
   '{"type": "object", "properties": { "default_rate_limit_per_min": { "type": "integer", "default": 60 }, "allow_write_api": { "type": "boolean", "default": false } } }'::jsonb,
   ARRAY[]::text[]),

  ('auto_backup', 'system', 'Automated backups', 'স্বয়ংক্রিয় ব্যাকআপ',
   'Scheduled database snapshots with verification.',
   'নির্ধারিত সময়ে ডেটাবেস স্ন্যাপশট, যাচাইসহ।',
   true, true, '{"frequency": "DAILY", "retention_days": 30, "verify_restore": true}'::jsonb,
   '{"type": "object", "properties": { "frequency": { "type": "string", "enum": ["DAILY", "TWICE_DAILY", "WEEKLY"], "default": "DAILY" }, "retention_days": { "type": "integer", "default": 30 }, "verify_restore": { "type": "boolean", "default": true } } }'::jsonb,
   ARRAY[]::text[]),

  ('manual_backup', 'system', 'Manual backup trigger', 'হাতে ব্যাকআপ চালু',
   'One-click snapshot before a risky change.',
   'ঝুঁকিপূর্ণ পরিবর্তনের আগে এক ক্লিকে স্ন্যাপশট।',
   true, true, '{}'::jsonb, NULL,
   ARRAY['auto_backup']::text[])
ON CONFLICT (key) DO UPDATE SET
  group_key = EXCLUDED.group_key,
  label_en = EXCLUDED.label_en,
  label_bn = EXCLUDED.label_bn,
  description_en = EXCLUDED.description_en,
  description_bn = EXCLUDED.description_bn,
  default_enabled = EXCLUDED.default_enabled,
  settings_schema = EXCLUDED.settings_schema,
  depends_on = EXCLUDED.depends_on;

-- Initial Platform Settings
INSERT INTO platform_settings (key, value_json, value_type, label_en, label_bn, group_key, is_sensitive)
VALUES
  ('default_saler_split_pct', '40.0'::jsonb, 'NUMBER', 'Default Saler Split Percentage', 'সেলার ডিফল্ট লাভ অংশ (%)', 'finance', false),
  ('default_platform_split_pct', '60.0'::jsonb, 'NUMBER', 'Default Platform Split Percentage', 'প্ল্যাটফর্ম ডিফল্ট লাভ অংশ (%)', 'finance', false),
  ('escrow_hold_days', '7'::jsonb, 'NUMBER', 'Default Escrow Hold Days', 'ডিফল্ট এসক্রো ধরে রাখার দিন', 'finance', false),
  ('min_payout_amount', '500'::jsonb, 'NUMBER', 'Minimum Payout Amount (BDT)', 'সর্বনিম্ন উত্তোলনের পরিমাণ (টাকা)', 'finance', false),
  ('cod_otp_threshold', '2000'::jsonb, 'NUMBER', 'COD OTP Threshold (BDT)', 'সিওডি ওটিপি সীমা (টাকা)', 'trust', false),
  ('jit_window_minutes', '120'::jsonb, 'NUMBER', 'Default JIT Window (Minutes)', 'ডিফল্ট জেআইটি সময় (মিনিট)', 'security', false),
  ('max_grant_days', '90'::jsonb, 'NUMBER', 'Maximum Standing Grant Duration (Days)', 'সর্বোচ্চ স্থায়ী অনুদানের মেয়াদ (দিন)', 'security', false),
  ('return_window_days', '7'::jsonb, 'NUMBER', 'Customer Return Window (Days)', 'ক্রেতা রিটার্ন সময়সীমা (দিন)', 'logistics', false)
ON CONFLICT (key) DO NOTHING;

-- Initial Global Commission Split Rule (40% saler, 60% platform)
INSERT INTO commission_rules (scope_type, scope_ref, saler_split_pct, platform_split_pct, min_margin_pct)
VALUES ('GLOBAL', NULL, 40.00, 60.00, 10.00);
