/**
 * masterTheme.js — applies a generated master palette to the live document.
 *
 * WHY a <style> element and not root.style.setProperty(): inline custom properties on <html> beat
 * every rule in themes.css, INCLUDING the `[data-theme='dark']` block. The Prompt 3.5 studio
 * pinned 33 semantic tokens inline, which is why a published theme silently disabled dark mode —
 * the light-mode hexes won in both. Emitting a stylesheet that mirrors themes.css's own four
 * blocks (base / OS-dark / explicit-dark / explicit-light) keeps the light-dark switch intact and
 * makes the whole generated theme legible in devtools instead of appearing as a wall of inline
 * styles with no provenance.
 *
 * Selectors are doubled (`:root:root`) so this stylesheet outranks themes.css regardless of
 * whether Vite injects a stylesheet after this element during HMR.
 */

import {
  generatePalette,
  BRAND_STEPS,
  NEUTRAL_STEPS,
} from './colorRamp.js';

const STYLE_ID = 'explooro-master-theme';
const STATUS_NAMES = ['success', 'warning', 'danger', 'info'];
const ACCENT_STEPS = [50, 100, 200, 300, 400, 500, 600, 700];

/** Semantic role maps carry a `__resolved` bag of hexes for the studio; it is not CSS. */
function declarations(roleMap, indent) {
  return Object.entries(roleMap)
    .filter(([prop]) => prop.startsWith('--'))
    .map(([prop, value]) => `${indent}${prop}: ${value};`)
    .join('\n');
}

/**
 * The raw ramps. Theme-independent by design (themes.css §1: "a ramp step is the same colour in
 * light and dark mode"), so they are emitted once and both themes read from them.
 */
function rampDeclarations(palette) {
  const lines = [];
  BRAND_STEPS.forEach((s) => lines.push(`    --brand-${s}: ${palette.brand[s]};`));
  NEUTRAL_STEPS.forEach((s) => lines.push(`    --neutral-${s}: ${palette.neutral[s]};`));
  STATUS_NAMES.forEach((name) => {
    Object.entries(palette[name]).forEach(([step, hex]) => {
      lines.push(`    --${name}-${step}: ${hex};`);
    });
  });
  ACCENT_STEPS.forEach((s) => lines.push(`    --accent-${s}: ${palette.accent[s]};`));
  return lines.join('\n');
}

export function buildMasterCss(palette) {
  const light = declarations(palette.roles.light, '    ');
  const dark = declarations(palette.roles.dark, '      ');
  const darkToggle = declarations(palette.roles.dark, '    ');
  const { meta, config } = palette;

  return `/* Generated by services/masterTheme.js — seed ${config.seed}, hue ${meta.seedHue},
   neutral hue ${meta.neutralHue} (${config.neutralMode}), accent hue ${meta.accentHue}
   (${config.accentHarmony}), brand anchored at step ${meta.anchorStep}. Do not hand-edit: this
   element is rewritten on every theme change. */

  :root:root {
${rampDeclarations(palette)}
  }

  /* Light (default) */
  :root:root {
${light}
  }

  /* Dark, following the OS preference — an explicit light toggle still outranks it below. */
  @media (prefers-color-scheme: dark) {
    :root:root:not([data-theme='light']) {
${dark}
    }
  }

  /* Dark, explicit toggle */
  :root:root[data-theme='dark'] {
${darkToggle}
  }

  /* Light, explicit toggle — last, so it wins the specificity tie against the OS-dark block. */
  :root:root[data-theme='light'] {
${light}
  }`;
}

function styleElement() {
  let el = document.getElementById(STYLE_ID);
  if (!el) {
    el = document.createElement('style');
    el.id = STYLE_ID;
    document.head.append(el);
  }
  return el;
}

let activePalette = null;

/**
 * Generates and mounts the palette for `masterConfig`. Returns the palette so callers can read
 * the resolved hexes (swatches, contrast readouts) without regenerating.
 */
export function applyMasterPalette(masterConfig) {
  const palette = generatePalette(masterConfig);
  styleElement().textContent = buildMasterCss(palette);
  activePalette = palette;
  return palette;
}

export function clearMasterPalette() {
  const el = document.getElementById(STYLE_ID);
  if (el) el.remove();
  activePalette = null;
}

export function getActiveMasterPalette() {
  return activePalette;
}

// Re-exported for the modules that already import them from here. They live in colorRamp.js
// because they are pure functions of a palette, and the SERVER needs them too — this module
// touches `document`, colorRamp.js does not.
export { paletteToSectionTokens, normaliseMasterConfig } from './colorRamp.js';
