/**
 * ResellerInsightsPage.js — Supplier Reseller Network Analytics & Curators Leaderboard (Prompt 11.1).
 *
 * Implements `idea proposition.md` §AL.1:
 * - Real-time analytics on which Salers curate and sell the supplier's products most effectively.
 * - Revenue, commission, and order volume breakdowns.
 * - Top regional demand breakdown with clean inline SVG charts (zero charting library).
 */

import { supplierApi } from '../../services/supplier.api.js';
import { t } from '../../services/i18n.js';
import { formatCurrency } from '../../services/format.js';
import { toast } from '../../services/toast.js';
import { Badge } from '../../components/ui/Badge.js';
import { EmptyState } from '../../components/ui/EmptyState.js';

export default function ResellerInsightsPage(root) {
  const container = document.createElement('div');
  container.className = 'supplier-resellers-page container py-6 space-y-6';

  let insights = null;
  let loading = true;

  async function loadInsights() {
    loading = true;
    render();
    try {
      const res = await supplierApi.getResellerInsights();
      insights = res.data || res || { top_salers: [], regional_distribution: [] };
    } catch (err) {
      console.error('Failed to load reseller insights:', err);
      toast.error(t('supplier.resellers_load_failed', 'Failed to load reseller insights.'));
      insights = { top_salers: [], regional_distribution: [] };
    } finally {
      loading = false;
      render();
    }
  }

  function render() {
    container.innerHTML = '';

    // 1. Header
    const header = document.createElement('header');
    header.className = 'page-header flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-subtle';
    header.innerHTML = `
      <div>
        <div class="flex items-center gap-2">
          <a href="/supplier" class="text-xs text-muted hover:text-primary">← ${t('supplier.back_to_dashboard', 'Dashboard')}</a>
        </div>
        <h1 class="text-2xl font-bold flex items-center gap-2 mt-1">
          <span>👥</span> ${t('supplier.reseller_insights_title', 'Reseller Network Insights & Curators')}
        </h1>
        <p class="text-sm text-muted mt-1">
          ${t('supplier.reseller_insights_subtitle', 'Identify your top-performing virtual storefront resellers, sales conversion, and geographic distribution.')}
        </p>
      </div>
      <div class="flex items-center gap-2">
        <button class="btn btn--sm btn--secondary" id="refresh-insights-btn">
          🔄 ${t('common.refresh', 'Refresh')}
        </button>
      </div>
    `;

    header.querySelector('#refresh-insights-btn').onclick = loadInsights;
    container.appendChild(header);

    if (loading) {
      const loader = document.createElement('div');
      loader.className = 'p-12 text-center text-muted';
      loader.innerHTML = `<div class="animate-spin inline-block w-8 h-8 border-4 border-primary border-t-transparent rounded-full mb-3"></div><p>${t('common.loading', 'Loading reseller network analytics...')}</p>`;
      container.appendChild(loader);
      return;
    }

    const topSalers = insights?.top_salers || [];
    const regionalDist = insights?.regional_distribution || [];

    // 2. Summary KPI Cards
    const totalRevenue = topSalers.reduce((acc, s) => acc + Number(s.total_revenue_generated || 0), 0);
    const totalOrders = topSalers.reduce((acc, s) => acc + Number(s.total_orders_sold || 0), 0);

    const kpiSummary = document.createElement('div');
    kpiSummary.className = 'grid grid-cols-1 md:grid-cols-3 gap-4';
    kpiSummary.innerHTML = `
      <div class="p-5 rounded-2xl border border-subtle bg-surface">
        <span class="text-xs text-muted uppercase font-semibold">${t('supplier.total_active_curators', 'Active Salers Sourcing Your SKUs')}</span>
        <div class="text-3xl font-bold mt-1 text-primary">${topSalers.length}</div>
        <p class="text-xs text-muted mt-1">Virtual storefronts with your items in stock</p>
      </div>
      <div class="p-5 rounded-2xl border border-subtle bg-surface">
        <span class="text-xs text-muted uppercase font-semibold">${t('supplier.reseller_order_volume', 'Total Orders via Resellers')}</span>
        <div class="text-3xl font-bold mt-1">${totalOrders}</div>
        <p class="text-xs text-muted mt-1">Direct retail orders generated by Salers</p>
      </div>
      <div class="p-5 rounded-2xl border border-subtle bg-surface">
        <span class="text-xs text-muted uppercase font-semibold">${t('supplier.reseller_gross_sales', 'Reseller Generated Sales')}</span>
        <div class="text-3xl font-bold mt-1 text-green-600">${formatCurrency(totalRevenue)}</div>
        <p class="text-xs text-muted mt-1">Gross merchandise volume through Saler stores</p>
      </div>
    `;
    container.appendChild(kpiSummary);

    // 3. Resellers Leaderboard & Geographic Demand (Side-by-Side)
    const contentGrid = document.createElement('div');
    contentGrid.className = 'grid grid-cols-1 lg:grid-cols-3 gap-6';

    // Top Salers Table (2 cols)
    const tableCard = document.createElement('div');
    tableCard.className = 'lg:col-span-2 p-5 rounded-2xl border border-subtle bg-surface space-y-4';
    tableCard.innerHTML = `
      <div class="flex items-center justify-between">
        <h3 class="font-bold text-base flex items-center gap-2">
          <span>🏆</span> ${t('supplier.top_curators_leaderboard', 'Top Resellers Leaderboard')}
        </h3>
        <span class="text-xs text-muted">Ranked by volume & sales</span>
      </div>
    `;

    if (topSalers.length === 0) {
      tableCard.appendChild(
        EmptyState({
          icon: '👥',
          title: t('supplier.no_resellers_yet', 'No resellers have curated your items yet'),
          description: t('supplier.no_resellers_desc', 'Offer attractive wholesale margins to entice Salers to feature your SKUs on their virtual storefronts.'),
        })
      );
    } else {
      let tableHtml = `
        <div class="overflow-x-auto">
          <table class="table w-full text-left text-xs border-collapse">
            <thead>
              <tr class="border-b border-subtle bg-surface-2 uppercase text-muted text-2xs">
                <th class="py-2.5 px-3"># Rank</th>
                <th class="py-2.5 px-3">${t('supplier.saler', 'Saler / Store')}</th>
                <th class="py-2.5 px-3">${t('supplier.curated_skus', 'Curated SKUs')}</th>
                <th class="py-2.5 px-3">${t('supplier.orders_sold', 'Orders')}</th>
                <th class="py-2.5 px-3 text-right">${t('supplier.revenue_generated', 'Revenue Generated')}</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-subtle">
      `;

      topSalers.forEach((saler, idx) => {
        const medal = idx === 0 ? '🥇' : idx === 1 ? '🥈' : idx === 2 ? '🥉' : `${idx + 1}`;
        tableHtml += `
          <tr class="hover:bg-surface-2 transition-colors">
            <td class="py-3 px-3 font-bold">${medal}</td>
            <td class="py-3 px-3">
              <div class="font-bold text-foreground">${saler.store_name || saler.saler_name}</div>
              <div class="text-2xs text-muted font-mono">${saler.store_slug ? `explooro.com/store/${saler.store_slug}` : saler.saler_phone}</div>
            </td>
            <td class="py-3 px-3">
              <span class="badge badge--neutral text-2xs">${saler.curated_products_count || 0} products</span>
            </td>
            <td class="py-3 px-3 font-bold">${saler.total_orders_sold || 0}</td>
            <td class="py-3 px-3 text-right font-mono font-bold text-green-600">
              ${formatCurrency(saler.total_revenue_generated || 0)}
            </td>
          </tr>
        `;
      });

      tableHtml += `</tbody></table></div>`;
      tableCard.innerHTML += tableHtml;
    }
    contentGrid.appendChild(tableCard);

    // Regional Demand SVG Bar Chart (1 col)
    const regionalCard = document.createElement('div');
    regionalCard.className = 'p-5 rounded-2xl border border-subtle bg-surface space-y-4';
    regionalCard.innerHTML = `
      <div class="flex items-center justify-between">
        <h3 class="font-bold text-base flex items-center gap-2">
          <span>📍</span> ${t('supplier.regional_demand', 'Regional Demand')}
        </h3>
        <span class="text-xs text-muted">Top Districts</span>
      </div>
    `;

    if (regionalDist.length === 0) {
      regionalCard.appendChild(
        EmptyState({
          icon: '📍',
          title: t('supplier.no_regional_data', 'No regional sales yet'),
          description: t('supplier.no_regional_desc', 'Geographic demand metrics will appear after delivered orders.'),
        })
      );
    } else {
      const maxSales = Math.max(...regionalDist.map((d) => Number(d.total_sales || 1)), 1);

      const chartWrapper = document.createElement('div');
      chartWrapper.className = 'space-y-3 pt-2';

      regionalDist.slice(0, 6).forEach((reg) => {
        const pct = Math.min(100, Math.round((Number(reg.total_sales) / maxSales) * 100));

        chartWrapper.innerHTML += `
          <div class="space-y-1">
            <div class="flex justify-between text-xs font-semibold">
              <span>${reg.district}</span>
              <span class="font-mono text-muted">${formatCurrency(reg.total_sales)} (${reg.order_count} orders)</span>
            </div>
            <div class="w-full h-2.5 bg-surface-2 rounded-full overflow-hidden border border-subtle">
              <div class="h-full bg-primary rounded-full transition-all duration-500" style="width: ${pct}%;"></div>
            </div>
          </div>
        `;
      });

      regionalCard.appendChild(chartWrapper);
    }

    contentGrid.appendChild(regionalCard);
    container.appendChild(contentGrid);
  }

  loadInsights();
  root.appendChild(container);

  return () => {
    container.remove();
  };
}
